### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.62.1_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by DanGiffen** [terraform-providers/terraform-provider-azurerm#12163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1

### Affected Resource(s)

azurerm_management_group

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/38534725/121561555-8388cc00-ca10-11eb-8609-9d4ebecd5c1b.png)

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

Stack trace from the terraform-provider-azurerm_v2.62.1_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x54baed8]

goroutine 110 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/managementgroup.resourceManagementGroupDelete(0xc0018b0d20, 0x5d50e40, 0xc00109b880, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/managementgroup/management_group_resource.go:300 +0x838
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000ce6140, 0xc000e370e0, 0xc000ff0720, 0x5d50e40, 0xc00109b880, 0x1, 0xc0014d59e0, 0x60df360)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:293 +0x4c6
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0001a3600, 0xc00131fa38, 0xc000e370e0, 0xc000ff0720, 0xc0014d5a68, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0xa5
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000007c18, 0x6c4b450, 0xc001850ff0, 0xc0018b0690, 0xc000007c18, 0xc001850ff0, 0xc001619ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6239760, 0xc000007c18, 0x6c4b450, 0xc001850ff0, 0xc0010aa2a0, 0x0, 0x6c4b450, 0xc001850ff0, 0xc00144a900, 0x205)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022d340, 0x6c91bd8, 0xc0005c4180, 0xc000312900, 0xc001238db0, 0xa08d9a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022d340, 0x6c91bd8, 0xc0005c4180, 0xc000312900, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000b6c840, 0xc00022d340, 0x6c91bd8, 0xc0005c4180, 0xc000312900)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-azurerm_v2.62.1_x5.exe plugin crashed!
### Expected Behaviour

replaced management group

### Actual Behaviour

panic plugin crashed

### Steps to Reproduce

1. `terraform apply plan.out'
### References

* #0000

**Comment by tombuildsstuff** [comment]
The cause of this is here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/dd5ea387f00a720c1b42f683972698419c372971/azurerm/internal/services/managementgroup/management_group_resource.go#L369
