### ISSUE TITLE
azurerm_kubernetes_cluster: panic on empty addon_profile

### ISSUE THREAD

**Issue by Segflow** [terraform-providers/terraform-provider-azurerm#12192]
### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.29
AzureRM v2.28.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
    name                = "myk8s"
    location            = azurerm_resource_group.rg.location
    resource_group_name = azurerm_resource_group.rg.name
    dns_prefix           = "aks"

    default_node_pool {
        name            = "agentpool"
        node_count      = 2
        vm_size         = "Standard_D2_v2"
    }

    identity {
        type = "SystemAssigned"
    }

    addon_profile {
    }

    network_profile {
        load_balancer_sku = "Standard"
        network_plugin = "kubenet"
    }
}
```

### Panic Output

```
2021-06-12T13:28:27.065Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: panic: interface conversion: interface {} is nil, not map[string]interface {}
2021-06-12T13:28:27.065Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0:
2021-06-12T13:28:27.065Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: goroutine 30 [running]:
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.expandKubernetesAddOnProfiles(0xc00150fee0, 0x1, 0x1, 0x4801a1d, 0x10, 0x4831ee1, 0x20, 0x4864936, 0x35, 0x483d356, ...)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/kubernetes_addons.go:179 +0x1164
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceArmKubernetesClusterCreate(0xc000bc0770, 0x416b5e0, 0xc000353b80, 0x0, 0x0)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/kubernetes_cluster_resource.go:692 +0x73f
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00043e3f0, 0xc00111fb30, 0xc000f3e000, 0x416b5e0, 0xc000353b80, 0x419e101, 0xc000bb8e58, 0xc00110fc20)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:310 +0x365
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00028a680, 0xc0015afa10, 0xc00111fb30, 0xc000f3e000, 0xc000bb8eb0, 0xc00020a820, 0x41a0380)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000111d8, 0x506be20, 0xc000bc8660, 0xc000bc02a0, 0xc0000111d8, 0xc000bc8660, 0xc000fe3b78)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x458eee0, 0xc0000111d8, 0x506be20, 0xc000bc8660, 0xc0015e7bc0, 0x0, 0x506be20, 0xc000bc8660, 0xc000bcb500, 0x9dc)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00028fb00, 0x50a8fc0, 0xc000102f00, 0xc000126600, 0xc000735b60, 0x896f480, 0x0, 0x0, 0x0)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x501
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00028fb00, 0x50a8fc0, 0xc000102f00, 0xc000126600, 0x0)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0008545d0, 0xc00028fb00, 0x50a8fc0, 0xc000102f00, 0xc000126600)
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa1
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2021-06-12T13:28:27.067Z [DEBUG] plugin.terraform-provider-azurerm_v2.28.0: 	/build/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa1
2021-06-12T13:28:27.072Z [DEBUG] plugin: plugin process exited: path=/nix/store/3sy11cbmhnni0fzp86y8z8944rb4s7bf-tf-plugin-env/bin/terraform-provider-azurerm_v2.28.0 pid=13303 error="exit status 2"
```

### Expected Behaviour

No panic

### Actual Behaviour

panic

### Steps to Reproduce

azurerm_kubernetes_cluster with empty `addon_profile `

**Comment by tombuildsstuff** [comment]
hi @Segflow 

Thanks for opening this issue.

Taking a look through here v2.28.0 of the Provider was released 9 months ago and there's been many changes to the Kubernetes resources since that time - as such we'd recommend upgrading to the latest version of the Azure Provider (v2.62.3) and seeing if that fixes this issue.

Should this still be an issue when using the latest provider then feel free to open a new issue and we can take a look - but I believe this has since been fixed so upgrading to the latest version of the Provider should help here.

Thanks!
