### ISSUE TITLE
Destroying storage container used in backend configuration with `terraform destroy` causes crash

### ISSUE THREAD

**Issue by TeamDman** [terraform-providers/terraform-provider-azurerm#12372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.1

### Affected Resource(s)

- `azurerm_storage_account`
- `azurerm_storage_container`
- terraform backend

### Terraform Configuration Files

A bunch of other unrelated modules were being deleted, but the main part should be similar to this

```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "myResourceGroup"
    storage_account_name = "tfstate1020910"
    container_name       = "tfstate"
    key                  = "main.tfstate"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.61.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">= 1.5.0"
    }
  }
}

data "azurerm_resource_group" "main" {
	name = var.resource_group_name
}

resource "azurerm_storage_account" "main" {
  name                     = var.storage_account_name
  resource_group_name      = data.azurerm_resource_group.main.name
  location                 = data.azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}


resource "azurerm_storage_container" "main" {
  name                  = var.storage_container_name
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}
```

### Debug Output

```
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

module.resource_group.azurerm_role_assignment.main: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/roleAssignments/235459fe-2da9-938c-d5bf-5ca61e967886]
module.virtual_machine_automation.azurerm_automation_connection_service_principal.main: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Automation/automationAccounts/myProject-VMStartStop/connections/AzureRunAsConnection]
module.virtual_machine_automation.azurerm_automation_job_schedule.evenings: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Automation/automationAccounts/myProject-VMStartStop/jobSchedules/7ab9689c-60d3-4d04-8233-ae0a885b5f41]
module.website_keys.azurerm_key_vault_secret.main["storage-key"]: Destroying... [id=https://site-keys.vault.azure.net/secrets/storage-key/1f9840f4fcf64a06b0cf90dbb628db9a]
module.service_principal_keys.azurerm_key_vault_secret.main["client-tenant"]: Destroying... [id=https://service-principal-keys.vault.azure.net/secrets/client-tenant/39a1f83e62a540e0b74ad964511b5b35]
module.service_principal_keys.azurerm_key_vault_secret.main["client-secret"]: Destroying... [id=https://service-principal-keys.vault.azure.net/secrets/client-secret/737527300f964c8db66b0d68c719e30b]
module.storage_account_keys.azurerm_key_vault_secret.main["tfstate-key"]: Destroying... [id=https://terraform-keys.vault.azure.net/secrets/tfstate-key/913beea82edc493581d4bafa871927c1]
module.service_principal_keys.azurerm_key_vault_secret.main["client-id"]: Destroying... [id=https://service-principal-keys.vault.azure.net/secrets/client-id/1b333961823b47ff8da2ae8f4a7aa2f4]
module.resource_group.azurerm_resource_group.main: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup]
module.virtual_machine.azurerm_linux_virtual_machine.main: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myProject-Agent]
module.virtual_machine_automation.azurerm_automation_job_schedule.evenings: Destruction complete after 0s
module.virtual_machine_automation.azurerm_automation_connection_service_principal.main: Destruction complete after 0s
module.virtual_machine_automation.azurerm_automation_job_schedule.mornings: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Automation/automationAccounts/myProject-VMStartStop/jobSchedules/b7613fb2-277b-48e2-915f-628b169c687f]
module.storage_account.azurerm_storage_container.main: Destroying... [id=https://tfstate1020910.blob.core.windows.net/tfstate]
module.virtual_machine_automation.azurerm_automation_job_schedule.mornings: Destruction complete after 0s
module.virtual_machine_automation.azurerm_automation_credential.example: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Automation/automationAccounts/myProject-VMStartStop/credentials/AzureCredential]
module.virtual_machine_automation.azurerm_automation_credential.example: Destruction complete after 1s
module.virtual_machine.azurerm_network_interface_security_group_association.main: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkInterfaces/myProject-Agent-NIC|/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkSecurityGroups/myProject-Agent-NSG]
module.resource_group.azurerm_role_assignment.main: Destruction complete after 1s
module.virtual_machine_automation.azurerm_automation_schedule.evenings: Destroying... [id=/subscriptions/abc/resourceGroups/myResourceGroup/providers/Microsoft.Automation/automationAccounts/myProject-VMStartStop/schedules/Evenings]
module.virtual_machine_automation.random_password.main: Destroying... [id=none]
module.virtual_machine_automation.random_password.main: Destruction complete after 0s
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Failed to save state
│
│ Error saving state: blobs.Client#PutBlockBlob: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404
│ Code="ContainerNotFound" Message="The specified container does not exist.\nRequestId:86cf5e91-b01e-0059-52e5-691601000000\nTime:2021-06-25T17:16:43.7905337Z"
╵
╷
│ Error: Failed to persist state to backend
│
│ The error shown above has prevented Terraform from writing the updated state to the configured backend. To allow for recovery, the state has been written to the file
│ "errored.tfstate" in the current working directory.
│
│ Running "terraform apply" again at this point will create a forked state, making it harder to recover.
│
│ To retry writing this state, use the following command:
│     terraform state push errored.tfstate
│
╵
╷
│ Error: Request cancelled
│
│   with module.virtual_machine_automation.azurerm_automation_certificate.main,
│   on modules\virtual-machine-automation\permissions.tf line 1, in resource "azurerm_automation_certificate" "main":
│    1: resource "azurerm_automation_certificate" "main" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.virtual_machine_automation.azurerm_automation_runbook.vm_start_stop,
│   on modules\virtual-machine-automation\runbook.tf line 1, in resource "azurerm_automation_runbook" "vm_start_stop":
│    1: resource "azurerm_automation_runbook" "vm_start_stop" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.virtual_machine_automation.azurerm_automation_schedule.mornings,
│   on modules\virtual-machine-automation\schedules.tf line 15, in resource "azurerm_automation_schedule" "mornings":
│   15: resource "azurerm_automation_schedule" "mornings" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Error releasing the state lock
│
│ Error message: failed to retrieve lock info: blobs.Client#GetProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be   
│ parsed: "" error: EOF
│
│ Terraform acquires a lock when accessing your state to prevent others
│ running Terraform to potentially modify the state at the same time. An
│ error occurred while releasing this lock. This could mean that the lock
│ did or did not release properly. If the lock didn't release properly,
│ Terraform may not be able to run future commands since it'll appear as if
│ the lock is held.
│
│ In this scenario, please call the "force-unlock" command to unlock the
│ state manually. This is a very dangerous operation since if it is done
│ erroneously it could result in two people modifying state at the same time.
│ Only call this command if you're certain that the unlock above failed and
│ that no one else is holding a lock.
╵

Stack trace from the terraform-provider-azurerm_v2.61.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x434a14e]

goroutine 236 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/azuresdkhacks.UpdateNetworkInterfaceAllowingRemovalOfNSG(0x620a818, 0xc0019f9a40, 0xc000a7e2c0, 0xc0014433c3, 0x25, 0xc001443417, 0x1b, 0xc00129cfc0, 0x0, 0xc000191800, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/azuresdkhacks/network_interface.go:27 +0x1ce
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network.resourceNetworkInterfaceSecurityGroupAssociationDelete(0xc001865810, 0x5321fa0, 0xc000332300, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/network_interface_network_security_group_association_resource.go:207 +0x937
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00081d860, 0xc000101cc0, 0xc001a701e0, 0x5321fa0, 0xc000332300, 0x24e901, 0xc001500c60, 0x56abc00)        
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:293 +0x4c6
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000191600, 0xc001441a38, 0xc000101cc0, 0xc001a701e0, 0x966d9a0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0xa5
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000964f8, 0x620a850, 0xc00140a480, 0xc001865420, 0xc0000964f8, 0xc00140a480, 0xc001517ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5804380, 0xc0000964f8, 0x620a850, 0xc00140a480, 0xc0019f9740, 0x0, 0x620a850, 0xc00140a480, 0xc00153f000, 0x3e1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002196c0, 0x6250898, 0xc001678000, 0xc001bce800, 0xc0010f2780, 0x9615820, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002196c0, 0x6250898, 0xc001678000, 0xc001bce800, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000286de0, 0xc0002196c0, 0x6250898, 0xc001678000, 0xc001bce800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-azurerm_v2.61.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

- Terraform reconfigures backend to use local state if it knows it's about to delete its own backend; maybe a warning is included before the approval step
- Terraform successfully deletes storage container

### Actual Behaviour

- Terraform successfully deleted the storage container
- Terraform crashed trying to save state in the deleted storage container

### Steps to Reproduce

1. Create storage container
2. Import container to terraform
3. Configure backend to use container
4. `terraform destroy`

**Comment by manicminer** [comment]
Hi @TeamDman, thanks for reporting this crash. If I understand your report correctly, destroying the same storage container in which you are storing your Terraform state for the current destroy operation, in the same module, is going to touch a lot of points and complete crash mitigation for such a scenario might not be possible. I think the best place to start is likely to be in the azure remote state backend rather than in the provider. As such, I'm going to close this issue as I believe this is likely where the stream of errors is originating from, and it's not clear whether this could be mitigated against at all in the provider. You might wish to raise this [upstream](https://github.com/hashicorp/terraform/issues), as that is where the backend resides.

I would suggest looking at strengthening your role assignments to prevent a Terraform user from doing this (probably a good idea in general given the sensitivity of your statefile) and it might be worth trying a delete lock on the storage account - although I'm not sure that would enforce against the container deletion.
