### ISSUE TITLE
Azurerm provider plugin crashed: error requested to post it here

### ISSUE THREAD

**Issue by JCZuurmond** [terraform-providers/terraform-provider-azurerm#12502]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 1.0.0
Azurerm version: 2.66

### Affected Resource(s)

N.A. I tried removing a couple resources for which I suspected the error was created, but that ended up moving the error.

### Terraform Configuration Files

N.A.

### Debug Output

None

### Panic Output

```
The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
details.
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v2.66.0_x5 plugin:

panic: reflect: call of reflect.Value.IsNil on array Value

goroutine 2538 [running]:
reflect.Value.IsNil(...)
	/opt/goenv/versions/1.16.3/src/reflect/value.go:1086
github.com/mitchellh/mapstructure.(*Decoder).decodeSlice(0xc001491920, 0x0, 0x0, 0x5513a40, 0xc001101a50, 0x546ed40, 0xc0007fbe78, 0x197, 0x8, 0x8)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:1086 +0x10ad
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc001491920, 0x0, 0x0, 0x5513a40, 0xc001101a50, 0x546ed40, 0xc0007fbe78, 0x197, 0xc0007fbe78, 0x197)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:460 +0x836
github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc001491920, 0x5513a40, 0xc001101a50, 0x0, 0xc0007fbe78)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:389 +0xf0
github.com/mitchellh/mapstructure.Decode(0x5513a40, 0xc001101a50, 0x53e0020, 0xc0007fbe78, 0x1, 0xc000d27bf0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:297 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc0007fbd28, 0xc002a94960, 0x3, 0x3, 0x5513a40, 0xc001101a50, 0xc0010b8c80, 0xc0010427f8, 0xc002a94930)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:127 +0xd2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc0007fbd28, 0xc002a94960, 0x3, 0x3, 0x5513a40, 0xc001101a50, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:103 +0xde
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc0007fbd28, 0xc001a804c0, 0x2, 0x2, 0x563cd60, 0xc002a94840, 0xc001cb0c80, 0x10, 0x54e0e20)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:225 +0x21a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc0007fbd28, 0xc001a804c0, 0x2, 0x2, 0x563cd60, 0xc002a94840, 0x4, 0xaf9495)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:109 +0x1de
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:123
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc0007fbd28, 0xc001101aa0, 0x1, 0x1, 0x546ed40, 0xc0007fbdb8, 0xc0010b9e00, 0x5e04135, 0xc001cb0640)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:143 +0x29e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc0007fbd28, 0xc001101aa0, 0x1, 0x1, 0x546ed40, 0xc0007fbdb8, 0x1, 0x1)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:103 +0xde
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc0007fbd28, 0xc001101aa0, 0x1, 0x1, 0x546ed40, 0xc0007fbdb8, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:89 +0x3f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc002928100, 0x5e04135, 0x4, 0x546ed40, 0xc0007fbdb8, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:227 +0x1df
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/storage.resourceStorageManagementPolicyRead(0xc002928100, 0x560bc60, 0xc000b90e00, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/storage/storage_management_policy_resource.go:295 +0x525
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0010af0a0, 0x655b5c8, 0xc0024ca3c0, 0xc002928100, 0x560bc60, 0xc000b90e00, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0010af0a0, 0x655b5c8, 0xc0024ca3c0, 0xc0002e9dc0, 0x560bc60, 0xc000b90e00, 0xc002258530, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0011420d8, 0x655b5c8, 0xc0024ca3c0, 0xc0024ca400, 0xc0024ca3c0, 0x40ba05, 0x591b140)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00082cb00, 0x655b670, 0xc0024ca3c0, 0xc00184cea0, 0xc00082cb00, 0xc002cdd770, 0xc0007d5ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x5ad47c0, 0xc00082cb00, 0x655b670, 0xc002cdd770, 0xc00184ce40, 0x0, 0x655b670, 0xc002cdd770, 0xc002477200, 0x402)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000766000, 0x65a4dd8, 0xc0007cb080, 0xc002a58c60, 0xc0007b8510, 0x9a7ab30, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000766000, 0x65a4dd8, 0xc0007cb080, 0xc002a58c60, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000be0aa0, 0xc000766000, 0x65a4dd8, 0xc0007cb080, 0xc002a58c60)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.66.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behaviour

No crash.

### Actual Behaviour

Crash.

### Steps to Reproduce

N.A. 

### Important Factoids

N.A.

### References

N.A.

**Comment by Wiston999** [comment]
Same issue here, same code is working with provider version 2.65.

**Comment by JCZuurmond** [comment]
It is happening since versioning `2.66.0` and it works for `2.65.0` as there is another issue detailing this #12473
