### ISSUE TITLE
`key_vault_access_policy`: crash on delete

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-azurerm#12576]
```

Stack trace from the terraform-provider-azurerm_v2.67.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c6ed39]

goroutine 234 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/keyvault.resourceKeyVaultAccessPolicyCreateOrDelete(0xc001d47600, 0x5633920, 0xc000fd4a80, 0x5e3127c, 0x6, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/keyvault/key_vault_access_policy_resource.go:181 +0x2019
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/keyvault.resourceKeyVaultAccessPolicyDelete(0xc001d47600, 0x5633920, 0xc000fd4a80, 0xc001f7a3c0, 0x5e3277f)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/keyvault/key_vault_access_policy_resource.go:273 +0x54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc000c38b60, 0x65892c8, 0xc0015d8a80, 0xc001d47600, 0x5633920, 0xc000fd4a80, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000c38b60, 0x65892c8, 0xc0015d8a80, 0xc00146b260, 0xc00127af20, 0x5633920, 0xc000fd4a80, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00072cf90, 0x65892c8, 0xc0015d8a80, 0xc001d1f040, 0xc0015d8a80, 0x5afe1c0, 0xc001279900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001cd7340, 0x6589370, 0xc0015d8a80, 0xc00146b180, 0xc001cd7340, 0xc001279980, 0xc000118ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5afe1c0, 0xc001cd7340, 0x6589370, 0xc001279980, 0xc0015dd380, 0x0, 0x6589370, 0xc001279980, 0xc0015e3500, 0x30e)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000232c40, 0x65d2fb8, 0xc000602d80, 0xc001323440, 0xc0019ccab0, 0x9ab7ba0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000232c40, 0x65d2fb8, 0xc000602d80, 0xc001323440, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000724c40, 0xc000232c40, 0x65d2fb8, 0xc000602d80, 0xc001323440)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.67.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


```

**Comment by aristosvo** [comment]
Seems like it cannot find the specific policy which it needs to delete (because of some changes outside of Terraform (?) and therefore having a nil pointer):

https://github.com/terraform-providers/terraform-provider-azurerm/blob/3b9d35824f846abc05af594812306024877d3577/azurerm/internal/services/keyvault/key_vault_access_policy_resource.go#L180-L181

I'll try to reproduce it by creating 2 policies, delete 1 manually and delete it again via TF:
```hcl
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                = "examplekeyvault2191"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "premium"
}

resource "azurerm_key_vault_access_policy" "example" {
  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions = [
    "Get",
  ]

  secret_permissions = [
    "Get",
  ]
}

resource "azurerm_key_vault_access_policy" "example2" {
  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions = [
    "List",
  ]

  secret_permissions = [
    "List",
  ]
}
```
