### ISSUE TITLE
azurerm_virtual_network_gateway_connection fails to import with provider panic.

### ISSUE THREAD

**Issue by elongstreet88** [terraform-providers/terraform-provider-azurerm#12650]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_virtual_network_gateway_connection`

### Terraform Configuration Files

```hcl
provider "azurerm" {
    alias  = "my-alias"
    subscription_id = "<my id>"
    features {}
}
data "azurerm_virtual_network_gateway" "my_connection" {
  name = "gw"
  resource_group_name = "gw-rg"
  provider = azurerm.my-alias
}
resource "azurerm_virtual_network_gateway_connection" "my_connection" {
  provider = azurerm.my-alias
  name = azurerm_express_route_circuit.primary.name
  resource_group_name = data.azurerm_virtual_network_gateway.my_connection.resource_group_name
  location = data.azurerm_virtual_network_gateway.my_connection.location

  type  = "ExpressRoute"
  express_route_circuit_id = azurerm_express_route_circuit.primary.id
  virtual_network_gateway_id  = data.azurerm_virtual_network_gateway.my_connection.id
  routing_weight  = 0
  authorization_key = "<key>"
}
```

### Debug Output

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.68.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x533c749]

goroutine 58 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network.resourceVirtualNetworkGatewayConnectionRead(0xc00199f180, 0x62999e0, 0xc0005a4000, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/virtual_network_gateway_connection_resource.go:386 +0x449
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a9e380, 0x71ffb08, 0xc00103cb80, 0xc00199f180, 0x62999e0, 0xc0005a4000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a9e380, 0x71ffb08, 0xc00103cb80, 0xc001c288c0, 0x62999e0, 0xc0005a4000, 0xc0002886f0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00040f500, 0x71ffb08, 0xc00103cb80, 0xc00103cbc0, 0xc00103cb80, 0x100b705, 0x65ad180)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00067ad40, 0x71ffbb0, 0xc00103cb80, 0xc0010406c0, 0xc00067ad40, 0xc0014821b0, 0xc0002a4ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6768140, 0xc00067ad40, 0x71ffbb0, 0xc0014821b0, 0xc001040660, 0x0, 0x71ffbb0, 0xc0014821b0, 0xc00106a380, 0x32d)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002348c0, 0x724a198, 0xc000250780, 0xc00163cc60, 0xc000696510, 0xa764d30, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002348c0, 0x724a198, 0xc000250780, 0xc00163cc60, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000b359e0, 0xc0002348c0, 0x724a198, 0xc000250780, 0xc00163cc60)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.68.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behaviour

`successful import`

### Actual Behaviour

`terraform crash`

### Steps to Reproduce

terraform import azurerm_virtual_network_gateway_connection.my_connection /subscriptions/<my_sub_id>/resourceGroups/<my_rg_name>/providers/Microsoft.Network/virtualNetworkGateways/<my_connection_name>

### Important Factoids

- importing across subscriptions
- first couple worked, a few didn't

### References

* #0000

**Comment by elongstreet88** [comment]
Oof, issue on my part.

I had the id for the virtual network gateway in the import instead of the virtual network connection id.

Updated import statement, and its working now.
