### ISSUE TITLE
Panic using 1.16.0 provider

### ISSUE THREAD

**Issue by simongh** [terraform-providers/terraform-provider-azurerm#2089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
terraform 0.11.8
azurerm provider 1.16.0

### Affected Resource(s)

Running terraform plan causes a panic. I'm limited in what I can share, as our infosec would have kittens, but I can share parts of the file if it'll help. It appears to be related to a network security rule.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

panic: runtime error: invalid memory address or nil pointer dereference

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
Hi @simongh,

I'm sorry to hear your having this issue. Could I trouble you to share the panic's full stack trace/log output? 

the part i am interested in looks something like this:

```
panic: interface conversion: interface {} is nil, not string

goroutine 112 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmSecurityCenterWorkspaceCreateUpdate(0xc420429180, 0x2d0f2e0, 0xc420165000, 0x24, 0x4088c20)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_security_center_workspace.go:52 +0x942
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420472ee0, 0xc42033a4b0, 0xc42000cf60, 0x2d0f2e0, 0xc420165000, 0xc4200e0401, 0x46, 0x0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x35a
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4205e7880, 0xc42033a0f0, 0xc42033a4b0, 0xc42000cf60, 0x1, 0xac780a57, 0x0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform.(*EvalApply).Eval(0xc42046eb00, 0x302c940, 0xc420416410, 0x2, 0x2, 0x2d43df4, 0x4)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform/eval_apply.go:57 +0x22c
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x2ff66a0, 0xc42046eb00, 0x302c940, 0xc420416410, 0x0, 0x0, 0x0, 0x0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc42000cac0, 0x302c940, 0xc420416410, 0x2, 0x2, 0x2d43df4, 0x4)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x7a
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x2ff6c00, 0xc42000cac0, 0x302c940, 0xc420416410, 0x2aa0180, 0x3ff8722, 0x2a2d4c0, 0xc42025cff0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform.Eval(0x2ff6c00, 0xc42000cac0, 0x302c940, 0xc420416410, 0xc42000cac0, 0x2ff6c00, 0xc42000cac0, 0xc420407be0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2cc1780, 0xc4203dc060, 0x0, 0x0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/terraform/graph.go:126 +0xc26
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc4203c6af0, 0x2cc1780, 0xc4203dc060, 0xc42037f640)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/dag/walk.go:387 +0x3a0
created by github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/dag.(*Walker).Update
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/dag/walk.go:310 +0x1248
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	15.745s
make: *** [testacc] Error 1
```

thanks!

**Comment by simongh** [comment]
I've got a very massive crash log. The best I can see is :

```
module.taskmanager.azurerm_network_interface.taskman - *terraform.NodePlannableResourceInstance
2018-10-16T11:03:03.885+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.15.0_x4.exe: panic: runtime error: invalid memory address or nil pointer dereference
2018-10-16T11:03:03.885+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.15.0_x4.exe: [signal 0xc0000005 code=0x0 addr=0x21 pc=0x175a795]
2018/10/16 11:03:03 [TRACE] dag/walk: added new vertex: "module.taskmanager.azurerm_network_interface.taskman"
2018/10/16 11:03:03 [TRACE] [walkPlan] Exiting eval tree: module.taskmanager.azurerm_network_security_rule.deny_all
2018-10-16T11:03:03.885+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.15.0_x4.exe: 
2018/10/16 11:03:03 [TRACE] vertex 'root.module.taskmanager.azurerm_network_security_rule.deny_all': expanding/walking dynamic subgraph
2018-10-16T11:03:03.885+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.15.0_x4.exe: goroutine 1778 [running]:
2018/10/16 11:03:03 [TRACE] root.taskmanager: eval: *terraform.EvalSequence
2018-10-16T11:03:03.885+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.15.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).readSet(0xc04283bd40, 0xc04245a390, 0x3, 0x3, 0xc042b2ca50, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018/10/16 11:03:03 [TRACE] [walkPlan] Exiting eval tree: module.taskmanager.azurerm_network_security_rule.allow_rule_ftps_xxxxx
2018/10/16 11:03:03 [TRACE] Graph after step *terraform.ResourceCountTransformer:
```
I'm not sure how useful this is, but this is the bit where it panics. The relevant HCL is, I think:
```
resource azurerm_network_interface taskman {
  name                = "${local.name}"
  location            = "${azurerm_resource_group.taskman.location}"
  resource_group_name = "${azurerm_resource_group.taskman.name}"

  ip_configuration {
    name                          = "${local.name}"
    subnet_id                     = "${azurerm_subnet.subnet.id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id          = "${azurerm_public_ip.taskman.id}"
  }

  tags {
    "managed-by" = "terraform"
    environment  = "${var.suffix}"
  }
}
```

**Comment by simongh** [comment]
hmmm. This specific block seems to cause problems. If I comment it out, no panic. Re-enable it panic. It seems related to the variables it's using, since other environments use this same block (it's in a module) without problem.

```
resource azurerm_sql_database primary {
  name                             = "${var.db_name}"
  resource_group_name              = "${data.azurerm_resource_group.core.name}"
  location                         = "${var.alt_location == "" ? data.azurerm_resource_group.core.location : var.alt_location}"
  server_name                      = "${var.db_server_name}"
  create_mode                      = "Default"
  edition                          = "${local.edition}"
  requested_service_objective_name = "${var.db_service_objective}"
  collation                        = "${local.collation}"

  tags {
    "managed-by" = "terraform"
    environment  = "${var.suffix}"
  }
}
```

**Comment by simongh** [comment]
I've tracked it down the `requested_service_objective_name` shown above. I was inadvertently setting this to "". In 1.14 this doesn't seem to cause an issue. In 1.15 & later, it causes a panic.

**Comment by katbyte** [comment]
Hi @simongh, 

Thank you for the effort in tracking down the cause! I have added validation to the property so it can no longer be empty in #2125 

However it is strange, the crash log is:

```
panic: runtime error: invalid memory address or nil pointer dereference
2018-10-20T20:40:07.337-0700 [DEBUG] plugin.terraform-provider-azurerm: [signal SIGSEGV: segmentation violation code=0x1 addr=0x21 pc=0x2465c1e]
2018-10-20T20:40:07.337-0700 [DEBUG] plugin.terraform-provider-azurerm:
2018-10-20T20:40:07.337-0700 [DEBUG] plugin.terraform-provider-azurerm: goroutine 90 [running]:
2018-10-20T20:40:07.337-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).readSet(0xc4201aeb70, 0xc4201aef60, 0x3, 0x3, 0xc420d442d0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.337-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:183 +0x19e
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).ReadField(0xc4201aeb70, 0xc4201aef60, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420386000, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:73 +0x6a0
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.readObjectField(0x2e05080, 0xc4201aeb70, 0xc4206123c0, 0x2, 0x2, 0xc4201aea50, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader.go:234 +0x245
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).ReadField(0xc4201aeb70, 0xc4206123c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:75 +0x5d8
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.readListField(0x2e05080, 0xc4201aeb70, 0xc42063bb90, 0x1, 0x1, 0xc420d440f0, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader.go:201 +0x420
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).ReadField(0xc4201aeb70, 0xc42063bb90, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:69 +0x299
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc420612160, 0xc42063bb90, 0x1, 0x1, 0x2c434ce, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:45 +0x1f7
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceDiff).get(0xc420d2dc00, 0xc42063bb90, 0x1, 0x1, 0x2c434ce, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go:406 +0xbc
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceDiff).GetOk(0xc420d2dc00, 0x2c5b706, 0x17, 0xc4201aeb70, 0xc420612120, 0xc420d2dc40)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go:338 +0xa6
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmSqlDatabase.func1(0xc420d2dc00, 0x2c07020, 0xc420534000, 0xc420601200, 0xc420d2dc00)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_sql_database.go:292 +0x44
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc420713b00, 0xc4204d24b0, 0xc4201916e0, 0x2cd2448, 0x2c07020, 0xc420534000, 0x102d6ab, 0xc420900a20, 0x100ca64)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:435 +0xabb
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc42052c930, 0xc4204d24b0, 0xc4201916e0, 0x2c07020, 0xc420534000, 0xc420190001, 0xc420900b88, 0x10bc98c)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0x160
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4203fcfc0, 0xc4204d2460, 0xc4204d24b0, 0xc4201916e0, 0x18, 0x18, 0xc420600ae0)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:296 +0xa4
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420406fc0, 0xc4206011a0, 0xc42077cc30, 0x0, 0x0)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:538 +0x57
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: reflect.Value.call(0xc42039ec60, 0xc4203ce580, 0x13, 0x2c3f6a3, 0x4, 0xc420900f18, 0x3, 0x3, 0xc4201c3780, 0x0, ...)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:447 +0x969
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: reflect.Value.Call(0xc42039ec60, 0xc4203ce580, 0x13, 0xc42050af18, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:308 +0xa4
2018-10-20T20:40:07.338-0700 [DEBUG] plugin.terraform-provider-azurerm: net/rpc.(*service).call(0xc420e9e500, 0xc4200c09b0, 0xc420ea3c30, 0xc420ea3c40, 0xc4201c4600, 0xc4204070a0, 0x28b0e20, 0xc4206011a0, 0x16, 0x28b0e60, ...)
2018-10-20T20:40:07.339-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/usr/local/Cellar/go/1.10.3/libexec/src/net/rpc/server.go:384 +0x14e
2018-10-20T20:40:07.339-0700 [DEBUG] plugin.terraform-provider-azurerm: created by net/rpc.(*Server).ServeCodec
2018-10-20T20:40:07.339-0700 [DEBUG] plugin.terraform-provider-azurerm: 	/usr/local/Cellar/go/1.10.3/libexec/src/net/rpc/server.go:480 +0x43a
2018/10/20 20:40:07 [ERROR] root: eval: *terraform.EvalDiff, err: unexpected EOF
2018/10/20 20:40:07 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/10/20 20:40:07 [TRACE] [walkPlan] Exiting eval tree: azurerm_sql_database.test
2018/10/20 20:40:07 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/10/20 20:40:07 [TRACE] dag/walk: upstream errored, not walking "provider.azurerm (close)"
2018/10/20 20:40:07 [TRACE] dag/walk: upstream errored, not walking "root"
2018-10-20T20:40:07.343-0700 [DEBUG] plugin: plugin process exited: path=/Users/kt/hashi/go/bin/terraform-provider-azurerm
2018/10/20 20:40:07 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-10-20T20:40:07.344-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

showing a crash on accessing the `threat_detection_policy`, and even weirder is if you remove `disabled_alerts` it works. Anyways for now validation will prevent the panic.

**Comment by tombuildsstuff** [comment]
@simongh taking a look at the Terraform Configuration posted above - just a heads up that from Terraform 0.12+ you'll need to ensure the resource names/ID's are quoted (this syntax is supported in older versions of Terraform too) 😄 e.g.

```
resource azurerm_sql_database primary {
```

needs to become

```
resource "azurerm_sql_database" "primary" {
```
