### ISSUE TITLE
Terraform 0.10.1 crashes when running terraform plan

### ISSUE THREAD

**Issue by paulv-quest** [terraform-providers/terraform-provider-azurerm#247]
Hi,

I just upgraded to 0.10.1 and `terraform plan` now crashes. The last few lines of the crash.log seem to indicate it's a problem with the azurerm plugin rather than terraform itself. I've gone back and double checked checked 0.10.0 and it works without any problems.

~The crash.log can be found at https://gist.githubusercontent.com/paulv-quest/2b89a6c5010401e691865eb36d197db8/raw/4aa235bceff1d33d0b405203f923c4db49b92d38/crash.log~ (edit: see the first comment)

Thanks,

Paul

**Comment by paulv-quest** [comment]
The crash.log is now at https://gist.github.com/paulv-quest/9a651c9688be8ac4afec5feb810f8488/raw/500a23f3487c6f2d2c551a46caf7d141ee6cf5b0/gistfile1.txt. The original contained my auth bearer token.

**Comment by ralfwierzbicki** [comment]
Same problem here:
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Server: Microsoft-HTTPAPI/2.0"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Strict-Transport-Security: max-age=31536000; includeSubDomains"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Vary: Accept-Encoding"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Correlation-Request-Id: 48171033-f3e2-4abf-b625-f6070e79c556"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Ratelimit-Remaining-Subscription-Reads: 14982"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Request-Id: 48171033-f3e2-4abf-b625-f6070e79c556"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Routing-Request-Id: NORTHCENTRALUS:20170816T043431Z:48171033-f3e2-4abf-b625-f6070e79c556"
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry=
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry=2f7
2017-08-16T00:34:31.806-0400 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry=
2017-08-16T00:34:31.806-0400 [ERROR] plugin.terraform-provider-azurerm_v0.1.5_x4: error parsing json from plugin: error="json: cannot unmarshal number into Go value of type map[string]interface {}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xb7752c]

goroutine 4089 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc42067eaf0, 0x3567a80, 0xc4203280a8)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:750 +0x39c
created by github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:544 +0xe2f

**Comment by tombuildsstuff** [comment]
Hey @paulv-quest @ralfwierzbicki 

Thanks for opening this issue - apologies that you're seeing this crash!

From what I can see this is an issue with Terraform Core - as such I've migrated this issue over to the main repository for one of the Terraform Core developers to take a look at: https://github.com/hashicorp/terraform/issues/15822

Thanks!
