### ISSUE TITLE
Terraform Crash on plan after adding new application_gateway

### ISSUE THREAD

**Issue by divgo** [terraform-providers/terraform-provider-azurerm#2817]
Terraform plan crashes AFTER successfully running a terraform apply and adding a new azurerm_application_gateway. Looking at the crash.log file, I see a ```panic: runtime error: index out of range``` right after it pulls the info about the application_gateway. 

### Terraform Version
Terraform v0.11.11
+ provider.azurerm v1.21.0

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "api_app_gateway" {
  name                = "payment-gateway-agw"
  resource_group_name = "${module.resource_group.name}"
  location            = "${module.resource_group.location}"


  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }


  gateway_ip_configuration {
    name      = "gateway-ip-configuration"
    subnet_id = "${module.app_gateway_subnet.id}"
  }


  frontend_port {
    name = "HTTPS"
    port = 443
  }


  ssl_certificate {
    name     = "payment-api"
    data     = "${base64encode(file(".\\payment-gateway-rg\\StageApiPayment.pfx"))}"
    password = "${var.devops_password}"
  }


  ssl_certificate {
    name     = "payment-authorization"
    data     = "${base64encode(file(".\\payment-gateway-rg\\StageAuthorizationPayment.pfx"))}"
    password = "${var.devops_password}"
  }


  authentication_certificate {
    name = "payment-api"
    data = "${base64encode(file(".\\payment-gateway-rg\\StageApiPayment.cer"))}"
  }


  frontend_ip_configuration {
    name                          = "FrontendIPConfig"
    subnet_id                     = "${module.app_gateway_subnet.id}"
    private_ip_address_allocation = "Dynamic"
  }


  probe {
    name                = "payment-api"
    path                = "/status"
    protocol            = "Https"
    host                = "stage.api.payment.domainname.com"
    interval            = 30
    timeout             = 30
    unhealthy_threshold = 3


    match {
      status_code = ["200-399"]
      body        = ""
    }
  }


  backend_address_pool {
    name = "payment-api"
  }


  backend_http_settings {
    name                  = "payment-api"
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 1
    probe_name            = "payment-api"


    authentication_certificate {
      name = "payment-api"
    }
  }


  backend_address_pool {
    name = "payment-authorization"
  }


  backend_http_settings {
    name                  = "payment-authorization"
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 1
    probe_name            = "payment-api"


    authentication_certificate {
      name = "payment-api"
    }
  }


  http_listener {
    name                           = "payment-api"
    frontend_ip_configuration_name = "FrontendIPConfig"
    frontend_port_name             = "HTTPS"
    protocol                       = "Https"
    host_name                      = "stage.api.payment.domainname.com"
    ssl_certificate_name           = "payment-api"
    require_sni                    = true
  }


  http_listener {
    name                           = "payment-authorization"
    frontend_ip_configuration_name = "FrontendIPConfig"
    frontend_port_name             = "HTTPS"
    protocol                       = "Https"
    host_name                      = "stage.authorization.payment.domainname.com"
    ssl_certificate_name           = "payment-authorization"
    require_sni                    = true
  }


  request_routing_rule {
    name                       = "payment-api"
    rule_type                  = "Basic"
    http_listener_name         = "payment-api"
    backend_address_pool_name  = "payment-api"
    backend_http_settings_name = "payment-api"
  }


  request_routing_rule {
    name                       = "payment-authorization"
    rule_type                  = "Basic"
    http_listener_name         = "payment-authorization"
    backend_address_pool_name  = "payment-authorization"
    backend_http_settings_name = "payment-authorization"
  }
}
```

### Crash Output
https://gist.github.com/divgo/3d0144e9f9fda16df0c097b948a14265

### Expected Behavior
terraform plan should have completed. 

### Actual Behavior
terraform plan crashes with attached output.

This is AFTER successfully running ```terraform apply``` and creating new resources. This is also right after updating terraform to 0.11.11 from 0.11.10

### Steps to Reproduce
terraform init --backend_config="access_key=%AZ_ACCESS_KEY%"
terraform apply --auto-approve
terraform plan

### Additional Context
nothing additional, just running terraform from a local command prompt

### References
None

**Comment by tombuildsstuff** [comment]
Relevant section from the crash log:

```
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: panic: runtime error: index out of range
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: goroutine 406 [running]:
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenApplicationGatewayAuthenticationCertificates(0xc00076bee0, 0xc000630000, 0x8, 0x21689c0, 0xc0007b77f0)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:991 +0x562
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmApplicationGatewayRead(0xc000630000, 0x24ba900, 0xc00061c000, 0xc000630000, 0x0)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:842 +0x64b
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc00061b110, 0xc000a8c050, 0x24ba900, 0xc00061c000, 0xc0007fa8a8, 0x4d4b01, 0x210cb40)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x167
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc0004143f0, 0xc000a8c000, 0xc000a8c050, 0xc00052c380, 0xc000ade0e0, 0x45306a0)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x99
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc0000041e0, 0xc0006dc010, 0xc0006dc0f0, 0x0, 0x0)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x55
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: reflect.Value.call(0xc0004846c0, 0xc0005b22e0, 0x13, 0x24f2f5b, 0x4, 0xc0002f5f18, 0x3, 0x3, 0xc000310040, 0x2819e60, ...)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:447 +0x45b
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: reflect.Value.Call(0xc0004846c0, 0xc0005b22e0, 0x13, 0xc0002f5f18, 0x3, 0x3, 0x0, 0x303, 0xc0007bd5d0)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:308 +0xab
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: net/rpc.(*service).call(0xc000178e40, 0xc000189400, 0xc00017bc08, 0xc00017bc30, 0xc000184600, 0xc000838060, 0x210cb00, 0xc0006dc010, 0x16, 0x210cb40, ...)
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:384 +0x155
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: created by net/rpc.(*Server).ServeCodec
2019-01-31T16:01:36.133-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4.exe: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:481 +0x485
2019/01/31 16:01:36 [ERROR] root.payment-gateway-rg.web_server1.network_interface: eval: *terraform.EvalRefresh, err: azurerm_network_interface.network_interface: unexpected EOF
```

and line: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.21.0/azurerm/resource_arm_application_gateway.go#L991

**Comment by pratik141** [comment]
Any workaround till this not fixed.

**Comment by jaekim09** [comment]
I think I am seeing this in my code too. Part of the panic error msg has similar lines. 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3430

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through I believe this is fixed and as such I'm going to close this issue for the moment - if your still encountering this using the latest version of the Azure Provider then please open a new issue with an updated stack trace and we'll take a look.

Thanks!
