### ISSUE TITLE
Possible issue with SPN credentials generated with Terraform?

### ISSUE THREAD

**Issue by MattMencel** [terraform-providers/terraform-provider-azurerm#3278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
> terraform -v
Terraform v0.11.13
+ provider.azurerm v1.25.0
```

### Affected Resource(s)

* `azuread_application`
* `azuread_service_principal`
* `azuread_service_principal_password`

### Expected Behavior

`az ad sp credential list --id ` for an SPN and credential created by Terraform should return information.

### Actual Behavior

```
az ad sp credential list --id 8ac6f6f2-...
The command failed with an unexpected error. Here is the traceback:

Parameter 'application_object_id' can not be None.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 400, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 1080, in list_service_principal_credentials
    return _get_service_principal_credentials(graph_client, app_object_id, cert)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 1087, in _get_service_principal_credentials
    app_creds = list(graph_client.applications.list_password_credentials(app_object_id))
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/azure/graphrbac/operations/applications_operations.py", line 669, in internal_paging
    'applicationObjectId': self._serialize.url("application_object_id", application_object_id, 'str'),
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 592, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.61/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 662, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'application_object_id' can not be None.
```

### Steps to Reproduce

Create an application, service principal, and service principal password.  This is my example...

```
resource "random_uuid" "spn_password" {}

resource "azuread_application" "spn" {
  name     = "${var.spn_name}"
  homepage = "${local.spn_url}"
}

resource "azuread_service_principal" "spn" {
  application_id = "${azuread_application.spn.application_id}"
}

resource "azuread_service_principal_password" "spn" {
  service_principal_id = "${azuread_service_principal.spn.id}"
  value                = "${random_uuid.spn_password.result}"
  end_date_relative    = "${var.spn_password_expiry}"
}
```

Try to retrieve the credential list in az cli for the new SPN.

````az ad sp credential list --id ```

### Important Factoids

If the SPN and credentials are generated using az cli instead of Terraform, the `credential list` command works.

### References

https://github.com/Azure/azure-cli/issues/8900

**Comment by neiltingley3** [comment]
I've just stumbled against the exact same error.

**Comment by katbyte** [comment]
Hi @MattMencel & @neilpeterson,

We are deprecating the AzureAd resources in the AzureRm provider in favour of the new AzureAD provider. I suggest trying it to see if it fixes the issue, if its not any bug fixes forthcomming will probably not be back ported to AzureRm.

As such i'm moving the issue there.

Thanks!
