### ISSUE TITLE
Provider crashes: apimgmt client is nil when logger is assigned

### ISSUE THREAD

**Issue by jcorioland** [terraform-providers/terraform-provider-azurerm#3563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Development version, built from master.

### Debug Output

```
Error: Error running plan: 1 error(s) occurred:

* provider.azurerm: unexpected EOF


panic: runtime error: invalid memory address or nil pointer dereference
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0x25c2697]
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: 
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: goroutine 58 [running]:
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.(*ArmClient).registerAPIManagementClients(0xc000c2a000, 0x3145435, 0x1d, 0xc000a5a3f0, 0x24, 0x353e380, 0xc00006a350)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/workspaces/gopath/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/config.go:506 +0x707
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.getArmClient(0xc00076f030, 0x313ef00, 0x0, 0x0, 0x5e89720, 0x24, 0x31188dd)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/workspaces/gopath/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/config.go:425 +0x4e2
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.providerConfigure.func1(0xc00076ef50, 0x0, 0xc000d05660, 0xc00076ef50, 0x0)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/workspaces/gopath/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/provider.go:476 +0x670
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc000cebb00, 0xc0008c8bd0, 0x8750d40, 0x0)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/workspaces/gopath/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:266 +0xd9
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Configure(0xc000d05080, 0xc0008c8bd0, 0xc000006930, 0x0, 0x0)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/workspaces/gopath/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:520 +0x45
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: reflect.Value.call(0xc000189c20, 0xc000006778, 0x13, 0x3115c79, 0x4, 0xc0009c5f18, 0x3, 0x3, 0xc000151640, 0xc000599000, ...)     
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/Go/src/reflect/value.go:447 +0x45b
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: reflect.Value.Call(0xc000189c20, 0xc000006778, 0x13, 0xc0009c5f18, 0x3, 0x3, 0xc000d05080, 0x0, 0x0)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/Go/src/reflect/value.go:308 +0xab
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: net/rpc.(*service).call(0xc000045e00, 0xc000a91900, 0xc00080d640, 0xc00080d650, 0xc000cebc00, 0xc000d05120, 0x2edd4c0, 0xc0008c8bd0, 0x16, 0x2bc6b40, ...)
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/Go/src/net/rpc/server.go:384 +0x155
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe: created by net/rpc.(*Server).ServeCodec
2019-05-31T11:01:37.165+0200 [DEBUG] plugin.terraform-provider-azurerm.exe:     C:/Go/src/net/rpc/server.go:481 +0x485
2019/05/31 11:01:37 [ERROR] root: eval: *terraform.EvalConfigProvider, err: unexpected EOF
2019/05/31 11:01:37 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/05/31 11:01:37 [ERROR] root: eval: *terraform.EvalOpFilter, err: unexpected EOF
2019/05/31 11:01:37 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/05/31 11:01:37 [TRACE] [walkPlan] Exiting eval tree: provider.azurerm
2019/05/31 11:01:37 [TRACE] dag/walk: upstream errored, not walking "azurerm_resource_group.main"
2019/05/31 11:01:37 [TRACE] dag/walk: upstream errored, not walking "azurerm_app_service_plan.main"
2019/05/31 11:01:37 [TRACE] dag/walk: upstream errored, not walking "azurerm_app_service.main"
2019/05/31 11:01:37 [TRACE] dag/walk: upstream errored, not walking "provider.azurerm (close)"
2019/05/31 11:01:37 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/05/31 11:01:37 [TRACE] dag/walk: upstream errored, not walking "root"
2019/05/31 11:01:37 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-05-31T11:01:37.167+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

This bug has been introducing by [this commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/1e72a1512e9e60a7167235428ea59a230077e879#diff-848235249455ee48aaf3ea5d431960ae). API Management client logger is assigned before the client is defined.

**Comment by jcorioland** [comment]
Already fixed in #3560, my bad!
