### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by V61K** [terraform-providers/terraform-provider-azurerm#3565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

please see log below.
https://github.com/terraform-providers/terraform-provider-azurerm/files/3240783/crash.log
### Actual Behavior

Running a (long?) script to create Service Fabric resources in a group, after errors were listed.
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

NO
### References

* #0000
[crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/3240783/crash.log)

**Comment by tombuildsstuff** [comment]
Stack trace:

```
2019-05-31T12:09:15.398+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: panic: runtime error: invalid memory address or nil pointer dereference
2019-05-31T12:09:15.398+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: [signal 0xc0000005 code=0x0 addr=0x10 pc=0x2480842]
2019-05-31T12:09:15.398+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 
2019-05-31T12:09:15.398+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: goroutine 971 [running]:
2019-05-31T12:09:15.402+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.retrieveLoadBalancerById(0xc000f806e0, 0xaa, 0x2de1ce0, 0xc00063a000, 0xaa, 0x0, 0x0, 0x0)
2019-05-31T12:09:15.402+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/loadbalancer.go:35 +0x352
2019-05-31T12:09:15.402+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmLoadBalancerRuleCreateUpdate(0xc0003b6380, 0x2de1ce0, 0xc00063a000, 0x0, 0x0)
2019-05-31T12:09:15.402+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_loadbalancer_rule.go:126 +0x1fb
2019-05-31T12:09:15.406+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002a9e30, 0xc000f62280, 0xc000134780, 0x2de1ce0, 0xc00063a000, 0x40bc01, 0xc00128fb80, 0x4d47d3)
2019-05-31T12:09:15.406+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x358
2019-05-31T12:09:15.406+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0006f5420, 0xc000f62230, 0xc000f62280, 0xc000134780, 0xc00032a380, 0x0, 0x1c0000)
2019-05-31T12:09:15.406+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa3
2019-05-31T12:09:15.406+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0001a5980, 0xc000134720, 0xc000137db0, 0x0, 0x0)
2019-05-31T12:09:15.406+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x5e
2019-05-31T12:09:15.408+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: reflect.Value.call(0xc0004504e0, 0xc0001460e0, 0x13, 0x2ea3294, 0x4, 0xc00128ff18, 0x3, 0x3, 0xc00013efc0, 0x0, ...)
2019-05-31T12:09:15.408+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x45b
2019-05-31T12:09:15.408+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: reflect.Value.Call(0xc0004504e0, 0xc0001460e0, 0x13, 0xc00128ff18, 0x3, 0x3, 0x0, 0x0, 0x0)
2019-05-31T12:09:15.408+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xab
2019-05-31T12:09:15.411+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: net/rpc.(*service).call(0xc0002100c0, 0xc000412190, 0xc0005a3de8, 0xc0005a3e10, 0xc00057a080, 0xc000f02460, 0x29a7a20, 0xc000134720, 0x16, 0x29a7a60, ...)
2019-05-31T12:09:15.411+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x155
2019-05-31T12:09:15.411+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: created by net/rpc.(*Server).ServeCodec
2019-05-31T12:09:15.411+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 
```

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here I believe this has been fixed, if your still encountering this on the latest release then please open a new issue with an updated stack trace and we'll take another look.

Thanks!
