### ISSUE TITLE
azurerm_role_definition unexpected EOF

### ISSUE THREAD

**Issue by salimkapadia** [terraform-providers/terraform-provider-azurerm#3732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform
- Terraform version: 0.11.13 
- terraform-provider-azurerm_v1.30.1_x4
- terraform-provider-random_v2.1.2_x4 

### Affected Resource(s)

* `azurerm_role_definition`

### Terraform Configuration Files

```hcl
data "local_file" "devops_allow" {
  filename = "${path.module}/files/devops_allow.txt"
}

locals {
  devops_allow      = "${sort(split(",", trimspace(replace(replace(data.local_file.devops_allow.content,"\n",""), "\"", ""))))}"
}

resource "random_uuid" "devops" {}

resource "azurerm_role_definition" "devops" {
  name               = "iam-devops"
  role_definition_id = "${random_uuid.devops.result}"
  scope              = "${data.azurerm_subscription.primary.id}"

  description = "This is a sample custom rule set"

  permissions {
    actions          = ["${local.devops_allow}"]
    not_actions      = ["${local.devops_deny}"]
    data_actions     = ["${local.devops_data_allow}"]
    not_data_actions = ["${local.devops_data_deny}"]
  }

  assignable_scopes = ["${var.resource_group_id}"] # will be resource group id
}

```

### Panic Output
https://gist.github.com/salimkapadia/5998cab4a6d16217bf4c10f067aaa8a4

### Context
I have moved all my permissions to a text file. These permissions look like this:
```
"*/read",
"Microsoft.Authorization/*/read",
"Microsoft.Cache/checknameavailability/action",
"Microsoft.Cache/locations/operationresults/read",
"Microsoft.Cache/operations/read",
```
 - The file has `LF` line endings. When the file is read, it contains new line characters which i replace with an empty string.
 - I also replace all double quotes with an empty string otherwise when its read, it tries to escape the quote. during the apply phase.

**Comment by leewilson86** [comment]
I have hit this error in TF v0.11.14, and when I switch to TF 0.12.8, I get the following error:

```
Error: rpc error: code = Unavailable desc = transport is closing
```

It looks like it could be related.

There is a TF dump
```
2019-09-06T15:40:06.429+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: [DEBUG] Determining which Resource Providers require Registration
2019-09-06T15:40:06.429+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: [DEBUG] All required Resource Providers are registered
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: provider.azurerm
2019/09/06 15:40:06 [TRACE] vertex "provider.azurerm": visit complete
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "data.azurerm_subscriptions.available (prepare state)"
2019/09/06 15:40:06 [TRACE] vertex "data.azurerm_subscriptions.available (prepare state)": starting visit (*terraform.NodeApplyableResource)
2019/09/06 15:40:06 [TRACE] vertex "data.azurerm_subscriptions.available (prepare state)": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: data.azurerm_subscriptions.available (prepare state)
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalWriteResourceState
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "module.roleAssignment.azurerm_role_assignment.roleAssignment (prepare state)"
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "module.roleDefinition.azurerm_role_definition.roleDefinition (prepare state)"
2019/09/06 15:40:06 [TRACE] vertex "module.roleAssignment.azurerm_role_assignment.roleAssignment (prepare state)": starting visit (*terraform.NodeApplyableResource)
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.azurerm_role_definition.roleDefinition (prepare state)": starting visit (*terraform.NodeApplyableResource)
2019/09/06 15:40:06 [TRACE] vertex "module.roleAssignment.azurerm_role_assignment.roleAssignment (prepare state)": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: module.roleAssignment.azurerm_role_assignment.roleAssignment (prepare state)
2019/09/06 15:40:06 [TRACE] module.roleAssignment: eval: *terraform.EvalWriteResourceState
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.azurerm_role_definition.roleDefinition (prepare state)": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: module.roleDefinition.azurerm_role_definition.roleDefinition (prepare state)
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalWriteResourceState
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: data.azurerm_subscriptions.available (prepare state)
2019/09/06 15:40:06 [TRACE] vertex "data.azurerm_subscriptions.available (prepare state)": visit complete
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "data.template_file.available_subscriptions (prepare state)"
2019/09/06 15:40:06 [TRACE] vertex "data.template_file.available_subscriptions (prepare state)": starting visit (*terraform.NodeApplyableResource)
2019/09/06 15:40:06 [TRACE] vertex "data.template_file.available_subscriptions (prepare state)": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: data.template_file.available_subscriptions (prepare state)
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalWriteResourceState
2019/09/06 15:40:06 [TRACE] GetResourceInstance: data.azurerm_subscriptions.available is a single instance
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: module.roleDefinition.azurerm_role_definition.roleDefinition (prepare state)
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.azurerm_role_definition.roleDefinition (prepare state)": visit complete
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: module.roleAssignment.azurerm_role_assignment.roleAssignment (prepare state)
2019/09/06 15:40:06 [TRACE] vertex "module.roleAssignment.azurerm_role_assignment.roleAssignment (prepare state)": visit complete
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: data.template_file.available_subscriptions (prepare state)
2019/09/06 15:40:06 [TRACE] vertex "data.template_file.available_subscriptions (prepare state)": visit complete
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "provider.template (close)"
2019/09/06 15:40:06 [TRACE] vertex "provider.template (close)": starting visit (*terraform.graphNodeCloseProvider)
2019/09/06 15:40:06 [TRACE] vertex "provider.template (close)": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: provider.template (close)
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "module.roleDefinition.var.assignableScopes"
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.var.assignableScopes": starting visit (*terraform.NodeApplyableModuleVariable)
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalCloseProvider
2019/09/06 15:40:06 [TRACE] GRPCProvider: Close
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.var.assignableScopes": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: module.roleDefinition.var.assignableScopes
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalSequence
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalOpFilter
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalModuleCallArgument
2019/09/06 15:40:06 [TRACE] GetResourceInstance: data.template_file.available_subscriptions has multiple keyed instances
2019-09-06T15:40:06.439+0100 [DEBUG] plugin: plugin process exited: path=/Users/Lee/.terraform.d/plugins/terraform-provider-template_v2.1.2_x4 pid=38360
2019-09-06T15:40:06.439+0100 [DEBUG] plugin: plugin exited
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: provider.template (close)
2019/09/06 15:40:06 [TRACE] vertex "provider.template (close)": visit complete
2019/09/06 15:40:06 [TRACE] <root>: eval: *terraform.EvalSetModuleCallArguments
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: module.roleDefinition.var.assignableScopes
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.var.assignableScopes": visit complete
2019/09/06 15:40:06 [TRACE] dag/walk: visiting "module.roleDefinition.azurerm_role_definition.roleDefinition[0]"
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.azurerm_role_definition.roleDefinition[0]": starting visit (*terraform.NodeApplyableResourceInstance)
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.azurerm_role_definition.roleDefinition[0]": evaluating
2019/09/06 15:40:06 [TRACE] [walkApply] Entering eval tree: module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalSequence
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalGetProvider
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalReadDiff
2019/09/06 15:40:06 [TRACE] EvalReadDiff: Read Create change from plan for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalIf
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: terraform.EvalNoop
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalIf
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalReadState
2019/09/06 15:40:06 [TRACE] EvalReadState: reading state for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] EvalReadState: no state present for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalReadDiff
2019/09/06 15:40:06 [TRACE] EvalReadDiff: Read Create change from plan for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalDiff
2019/09/06 15:40:06 [TRACE] Re-validating config for "module.roleDefinition.azurerm_role_definition.roleDefinition[0]"
2019/09/06 15:40:06 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2019/09/06 15:40:06 [TRACE] GRPCProvider: PlanResourceChange
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalCheckPlannedChange
2019/09/06 15:40:06 [TRACE] EvalCheckPlannedChange: Verifying that actual change (action Create) matches planned change (action Create)
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalGetProvider
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalReadState
2019/09/06 15:40:06 [TRACE] EvalReadState: reading state for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] EvalReadState: no state present for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalReduceDiff
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalIf
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: terraform.EvalNoop
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalApplyPre
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalApply
2019/09/06 15:40:06 [DEBUG] module.roleDefinition.azurerm_role_definition.roleDefinition[0]: applying the planned Create change
2019/09/06 15:40:06 [TRACE] GRPCProvider: ApplyResourceChange
module.roleDefinition.azurerm_role_definition.roleDefinition[0]: Creating...
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 
Error: rpc error: code = Unavailable desc = transport is closing


Releasing state lock. This may take a few moments...
panic: interface conversion: interface {} is nil, not string
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: goroutine 59 [running]:
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.expandRoleDefinitionPermissions(0xc0002ad260, 0xc0005e0ce0, 0xb, 0x3be7880)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_role_definition.go:247 +0xab1
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmRoleDefinitionCreateUpdate(0xc0002ad260, 0x3dc13c0, 0xc000580500, 0x2, 0x7868aa0)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_role_definition.go:118 +0x21a
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000408480, 0xc000ce6320, 0xc0007c6b40, 0x3dc13c0, 0xc000580500, 0xc00065bb01, 0xc00097a098, 0x3c9c840)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:287 +0x3b4
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000742200, 0xc000a57a30, 0xc000ce6320, 0xc0007c6b40, 0xc000638868, 0xc0000b6f28, 0x3c9ed60)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e9f0, 0x47ee220, 0xc000510000, 0xc00097c060, 0xc00000e9f0, 0xc000510000, 0xc0006c0ba8)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:885 +0x894
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x3fe47c0, 0xc00000e9f0, 0x47ee220, 0xc000510000, 0xc000ce6050, 0x0, 0x47ee220, 0xc000510000, 0xc000656000, 0x1b2c)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008b200, 0x4839760, 0xc0000b4d80, 0xc00061e000, 0xc00056f1d0, 0x783ba00, 0x0, 0x0, 0x0)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:972 +0x470
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00008b200, 0x4839760, 0xc0000b4d80, 0xc00061e000, 0x0)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1252 +0xda6
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000436b30, 0xc00008b200, 0x4839760, 0xc0000b4d80, 0xc00061e000)
2019-09-06T15:40:06.492+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:691 +0x9f
2019-09-06T15:40:06.493+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-09-06T15:40:06.493+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.33.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:689 +0xa1
2019-09-06T15:40:06.497+0100 [DEBUG] plugin: plugin process exited: path=/Users/Lee/Code/terraform/Terraform.Environments/rbac/.terraform/plugins/darwin_amd64/terraform-provider-azurerm_v1.33.0_x4 pid=38358 error="exit status 2"
2019/09/06 15:40:06 [DEBUG] module.roleDefinition.azurerm_role_definition.roleDefinition[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalMaybeTainted
2019/09/06 15:40:06 [TRACE] EvalMaybeTainted: module.roleDefinition.azurerm_role_definition.roleDefinition[0] encountered an error during creation, so it is now marked as tainted
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalWriteState
2019/09/06 15:40:06 [TRACE] EvalWriteState: removing state object for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalApplyProvisioners
2019/09/06 15:40:06 [TRACE] EvalApplyProvisioners: azurerm_role_definition.roleDefinition[0] has no state, so skipping provisioners
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalMaybeTainted
2019/09/06 15:40:06 [TRACE] EvalMaybeTainted: module.roleDefinition.azurerm_role_definition.roleDefinition[0] encountered an error during creation, so it is now marked as tainted
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalWriteState
2019/09/06 15:40:06 [TRACE] EvalWriteState: removing state object for module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalIf
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalIf
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalWriteDiff
2019/09/06 15:40:06 [TRACE] module.roleDefinition: eval: *terraform.EvalApplyPost
2019/09/06 15:40:06 [ERROR] module.roleDefinition: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/09/06 15:40:06 [ERROR] module.roleDefinition: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/06 15:40:06 [TRACE] [walkApply] Exiting eval tree: module.roleDefinition.azurerm_role_definition.roleDefinition[0]
2019/09/06 15:40:06 [TRACE] vertex "module.roleDefinition.azurerm_role_definition.roleDefinition[0]": visit complete
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "module.roleDefinition.output.roleDefinitionId" errored, so skipping
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "module.roleAssignment.var.roleDefinitionId" errored, so skipping
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "module.roleAssignment.azurerm_role_assignment.roleAssignment[0]" errored, so skipping
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "module.roleAssignment.output.roleAssignmentId" errored, so skipping
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "provider.azurerm (close)" errored, so skipping
2019/09/06 15:40:06 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019-09-06T15:40:07.321+0100 [DEBUG] plugin: plugin exited
make: *** [apply] Error 1

```

**Comment by joekhese** [comment]
please what's the solution to this issue? its turning into a real blocker
