### ISSUE TITLE
Crash Refreshing State For azurerm_virtual_machine_scale_set "Unexpected EOF"

### ISSUE THREAD

**Issue by dustman9000** [terraform-providers/terraform-provider-azurerm#4390]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.11.11
+ provider.azurerm v1.34.0
```

### Affected Resource(s)

* `azurerm_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_scale_set" "vmss" {
  name                = "${var.prefix}-${var.env}-${var.location}-${var.name}-vmss"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  upgrade_policy_mode = "Manual"
  priority            = "Regular"

  sku {
    name     = "${var.vm_size}"
    tier     = "Standard"
    capacity = "${var.capacity}"
  }

  storage_profile_image_reference = ["${var.storage_profile_image_reference}"]

  boot_diagnostics = ["${var.boot_diagnostics}"]

  storage_profile_os_disk {
    name = ""

    #name          = "${var.prefix}-${var.env}-${var.location}-${var.name}-osdisk"
    caching       = "ReadWrite"
    create_option = "FromImage"

    #vhd_containers = ["${azurerm_storage_account.vm_storage.primary_blob_endpoint}${azurerm_storage_container.vm_cont.name}"]
    managed_disk_type = "Standard_LRS"
  }

  storage_profile_data_disk {
    disk_size_gb  = "${var.data_disk_size_gb}"
    caching       = "ReadWrite"
    create_option = "${var.storage_profile_data_disk_create_option}"
    lun           = 0
  }

  os_profile {
    computer_name_prefix = "${var.vm_computer_name != "" ? var.vm_computer_name : var.name}"
    admin_username       = "${var.vm_username}"
    admin_password       = "${var.vm_password}"
  }

  os_profile_windows_config {
    provision_vm_agent        = true
    enable_automatic_upgrades = true
    provision_vm_agent        = true
  }

  network_profile {
    name    = "${var.prefix}-${var.env}-${var.location}-${var.name}-network"
    primary = true

    ip_configuration {
      name      = "IPConfiguration"
      primary   = true
      subnet_id = "${data.azurerm_subnet.private_subnet.id}"
    }
  }
}
```

### Panic Output

https://gist.github.com/dustman9000/93e77b2f61f41af1d128c79896ac03bf

### Expected Behavior

A `terraform plan` and `terraform apply` works.

### Actual Behavior

Running `terraform plan` causes terraform to crash while refreshing state. 

```
panic: runtime error: invalid memory address or nil pointer dereference
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b7d9af]
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4:
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: goroutine 44 [running]:
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenAzureRmVirtualMachineScaleSetBootDiagnostics(...)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine_scale_set.go:1189
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmVirtualMachineScaleSetRead(0xc0003d0540, 0x305cd00, 0xc000736000, 0xc0003d0540, 0x0)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine_scale_set.go:965 +0x1c1f
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc0003af420, 0xc0000ac640, 0x305cd00, 0xc000736000, 0xc00071fc28, 0x10bf901, 0x2cad180)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc0003ca070, 0xc0000ac5f0, 0xc0000ac640, 0xc000086800, 0x18, 0x5a006c0)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00017f340, 0xc0009d67c0, 0xc0009d69e0, 0x0, 0x0)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: reflect.Value.call(0xc000161980, 0xc00000c928, 0x13, 0x3094dde, 0x4, 0xc00009cf18, 0x3, 0x3, 0xc000461c40, 0xc0000d8900, ...)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:447 +0x454
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: reflect.Value.Call(0xc000161980, 0xc00000c928, 0x13, 0xc000064f18, 0x3, 0x3, 0xc000239500, 0xc000064f01, 0xc000060101)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:308 +0xa4
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: net/rpc.(*service).call(0xc000461f40, 0xc000488b90, 0xc00050bd20, 0xc00050bd30, 0xc0001cc980, 0xc00017fe60, 0x2cad140, 0xc0009d67c0, 0x16, 0x2cad180, ...)
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:384 +0x14e
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: created by net/rpc.(*Server).ServeCodec
2019-09-19T16:14:09.046-0700 [DEBUG] plugin.terraform-provider-azurerm_v1.21.0_x4: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:481 +0x47e
2019/09/19 16:14:09 [ERROR] root.cts_primary: eval: *terraform.EvalRefresh, err: azurerm_virtual_machine_scale_set.vmss: unexpected EOF
2019/09/19 16:14:09 [ERROR] root.cts_primary: eval: *terraform.EvalSequence, err: azurerm_virtual_machine_scale_set.vmss: unexpected EOF
2019/09/19 16:14:09 [TRACE] [walkImport] Exiting eval tree: import module.cts_primary.azurerm_virtual_machine_scale_set.vmss result: /subscriptions/82e80723-ea2a-4bbb-8798-5886a138414a/resourceGroups/smc-dev01-eastasia/providers/Microsoft.Compute/virtualMachineScaleSets/smc-dev01-eastasia-cts1-vmss
2019/09/19 16:14:09 [TRACE] dag/walk: upstream errored, not walking "provider.azurerm (close)"
2019/09/19 16:14:09 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-09-19T16:14:09.049-0700 [DEBUG] plugin: plugin process exited: path=/Users/dustin/src/terraform/providers/azure-dev/dev/dev01/eastasia/app-services/.terraform/plugins/darwin_amd64/terraform-provider-azurerm_v1.21.0_x4
2019-09-19T16:14:09.049-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

1. Using 
2. `terraform plan`
2. `terraform import azurerm_virtual_machine_scale_set.scaleset1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Compute/virtualMachineScaleSets/scaleset1`
3. `terraform refresh`

### Important Factoids

This was working just fine for months, but all of a sudden coming back to modify the resource and it crashes while refreshing state. 

If I remove the azurerm_virtual_machine_scale_set from the tfstate file and re-run the plan, everything works fine.

### References

* #0000

**Comment by KyMidd** [comment]
We're seeing the same behavior with TF 0.14.4 (most recent as of today) and AzureRM provider 2.41.0 (also most recent as of today) as well as older TF and provider versions. This interestingly worked until recently, and is only affecting one VM scale-set resource, but not another. This popped up recently when doing a refresh, and had worked previously. 

We see the same behavior when importing the existing (tainted?) scale-set resource. 

```
$ terraform import module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Ue1NePrdResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/Ue1NeAdoLinVmSS
module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Ue1NePrdResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/Ue1NeAdoLinVmSS"...
module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent: Import prepared!
  Prepared azurerm_virtual_machine_scale_set for import
module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Ue1NePrdResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/Ue1NeAdoLinVmSS]

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48b1d36]
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: goroutine 32 [running]:
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.flattenAzureRmVirtualMachineScaleSetBootDiagnostics(...)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/virtual_machine_scale_set_resource.go:1250
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.resourceArmVirtualMachineScaleSetRead(0xc000fa64d0, 0x55a8a80, 0xc00084c300, 0x0, 0x0)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/virtual_machine_scale_set_resource.go:1028 +0x1a96
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000203c20, 0xc0005297c0, 0x55a8a80, 0xc00084c300, 0xc00000f058, 0x0, 0x0)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x129
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000eb08, 0x62fc000, 0xc00105c1b0, 0xc00133c0c0, 0xc00000eb08, 0xc00105c1b0, 0xc00096db78)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x59f9ac0, 0xc00000eb08, 0x62fc000, 0xc00105c1b0, 0xc00133c060, 0x0, 0x62fc000, 0xc00105c1b0, 0xc00106ae00, 0x370)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000583e00, 0x6340a80, 0xc000001980, 0xc000850000, 0xc000722b40, 0x90cff30, 0x0, 0x0, 0x0)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x522
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc000583e00, 0x6340a80, 0xc000001980, 0xc000850000, 0x0)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd34
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0007a6820, 0xc000583e00, 0x6340a80, 0xc000001980, 0xc000850000)
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa5
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-07T17:46:25.219-0600 [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa5
2021-01-07T17:46:25.231-0600 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.41.0/darwin_amd64/terraform-provider-azurerm_v2.41.0_x5 pid=98463 error="exit status 2"
2021/01/07 17:46:25 [TRACE] vertex "import module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent result": visit complete
2021/01/07 17:46:25 [TRACE] vertex "module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent (import id \"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Ue1NePrdResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/Ue1NeAdoLinVmSS\")": dynamic subgraph encountered errors
2021/01/07 17:46:25 [TRACE] vertex "module.linux_ado_builder.azurerm_virtual_machine_scale_set.linux_devops_agent (import id \"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Ue1NePrdResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/Ue1NeAdoLinVmSS\")": visit complete
2021/01/07 17:46:25 [TRACE] dag/walk: upstream of "module.linux_ado_builder (close)" errored, so skipping
2021/01/07 17:46:25 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2021/01/07 17:46:25 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/07 17:46:25 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/07 17:46:25 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-01-07T17:46:25.234-0600 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

The AzureRM provider stanza referenced by the trace is: 
```
if diagnosticsProfile := profile.DiagnosticsProfile; diagnosticsProfile != nil {
  if bootDiagnostics := diagnosticsProfile.BootDiagnostics; bootDiagnostics != nil {
    flattenedDiagnostics := flattenAzureRmVirtualMachineScaleSetBootDiagnostics(bootDiagnostics)
    // TODO: rename this field to `diagnostics_profile`
    if err := d.Set("boot_diagnostics", flattenedDiagnostics); err != nil {
      return fmt.Errorf("[DEBUG] Error setting `boot_diagnostics`: %#v", err)
    }
  }
}
```

Focused on this line in particular: 
```
flattenedDiagnostics := flattenAzureRmVirtualMachineScaleSetBootDiagnostics(bootDiagnostics)
```

I do see that there are new resource types that we should likely be using: azurerm_linux_virtual_machine_scale_set && azurerm_windows_virtual_machine_scale_set. I'll work with our team to rewrite to this new resource type and see if issues resolve.

**Comment by tombuildsstuff** [comment]
👋 

At this point in time the older `azurerm_virtual_machine_scale_set` resource has been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources. Since the older `azurerm_virtual_machine_scale_set` resource has fallen out of sync from the behaviour of the Azure API, to avoid unintentionally breaking users relying on this behaviour the older resources are feature-frozen.

As this resource is feature-frozen to maintain compatibility, I'm going to close this issue for the moment - but I'd recommend instead checking out the `azurerm_linux_virtual_machine_scale_set` resource, which better represents how the Azure API behaves for this resource.

Thanks!
