### ISSUE TITLE
(1.35.0) Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by cwebbtw** [terraform-providers/terraform-provider-azurerm#4641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
2019/10/17 11:50:47 [INFO] Terraform version: 0.12.10  
2019/10/17 11:50:47 [INFO] Go runtime version: go1.12.9
2019/10/17 11:50:47 [DEBUG] plugin requirements: "helm"=""
2019/10/17 11:50:47 [DEBUG] plugin requirements: "azurerm"="=1.35.0"
2019/10/17 11:50:47 [DEBUG] plugin requirements: "kubernetes"="=1.6.2"
```

### Debug Output

See debug log: -

[debug.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/3739019/debug.log)

### Panic Output

See crash log:

[crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/3739008/crash.log)

```
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b483d8]
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: goroutine 99 [running]:
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.dataSourceArmClientConfigRead(0xc0003ca2a0, 0x321a320, 0xc0004fbb00, 0xc0003ca2a0, 0x0)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_client_config.go:87 +0x378
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc0004a6600, 0xc00084c300, 0x321a320, 0xc0004fbb00, 0xc00015fb18, 0x1, 0x0)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:398 +0x88
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000578880, 0xc000bbfaf0, 0xc00084c300, 0xc00084c300, 0x0, 0x0)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:446 +0x17f
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc0000e31d0, 0x3f976c0, 0xc0006b6a20, 0xc00084e0c0, 0xc0000e31d0, 0xc0006b6a20, 0xc00078cba8)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:1036 +0x45f
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadDataSource_Handler(0x36c6040, 0xc0000e31d0, 0x3f976c0, 0xc0006b6a20, 0xc000ba2280, 0x0, 0x3f976c0, 0xc0006b6a20, 0xc00047a0a0, 0x92)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3253 +0x23e
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00059ad80, 0x3fe4e40, 0xc00059bb00, 0xc00017a100, 0xc00060b650, 0x760d470, 0x0, 0x0, 0x0)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:972 +0x470
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00059ad80, 0x3fe4e40, 0xc00059bb00, 0xc00017a100, 0x0)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1252 +0xda6
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005e0230, 0xc00059ad80, 0x3fe4e40, 0xc00059bb00, 0xc00017a100)
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:691 +0x9f
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-17T11:37:40.376Z [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:689 +0xa1
2019-10-17T11:37:40.378Z [DEBUG] plugin: plugin process exited: path=/home/jenkins/workspace/API_SERVICE_INFRA_PIPELINE/app-infrastructure/.terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.35.0_x4 pid=1074 error="exit status 2"
2019/10/17 11:37:40 [ERROR] <root>: eval: *terraform.EvalRead
```

### Expected Behavior

Infrastructure should have created successfully

### Actual Behavior

Panic/Crash

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using MSI

### References

N/A

* #0000

**Comment by rudolphjacksonm** [comment]
Getting the same thing on my end when running a `terraform plan`:
```
Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is nil, not map[string]interface {}
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: goroutine 287 [running]:
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenAzureRmKubernetesClusterServicePrincipalProfile(0xc000a70240, 0xc0002cc3f0, 0x19, 0x3e7ece0, 0xc0007d1680)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_kubernetes_cluster.go:1593 +0x370
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmKubernetesClusterRead(0xc0002cc3f0, 0x3e18720, 0xc000984480, 0xc0002cc3f0, 0x0)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_kubernetes_cluster.go:902 +0x163c
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000184100, 0xc000b00410, 0x3e18720, 0xc000984480, 0xc000a14150, 0xc000b00410, 0x0)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:455 +0x119
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000164600, 0x4b95d80, 0xc000500180, 0xc000b002d0, 0xc000164600, 0xc000500180, 0xc000c31ba8)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:525 +0x3d7
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x42c4620, 0xc000164600, 0x4b95d80, 0xc000500180, 0xc000b00190, 0x0, 0x4b95d80, 0xc000500180, 0xc000ca2000, 0x6852)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3181 +0x23e
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000556a80, 0x4be3780, 0xc000556d80, 0xc0005f6000, 0xc0007cf170, 0x820f510, 0x0, 0x0, 0x0)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:972 +0x470
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000556a80, 0x4be3780, 0xc000556d80, 0xc0005f6000, 0x0)
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1252 +0xda6
2019-10-24T12:00:39.568+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000488690, 0xc000556a80, 0x4be3780, 0xc000556d80, 0xc0005f6000)
2019-10-24T12:00:39.569+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:691 +0x9f
2019-10-24T12:00:39.569+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-24T12:00:39.569+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:689 +0xa1
2019/10/24 12:00:39 [ERROR] module.aks-cluster: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/10/24 12:00:39 [ERROR] module.aks-cluster: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/10/24 12:00:39 [TRACE] [walkRefresh] Exiting eval tree: module.aks-cluster.azurerm_kubernetes_cluster.aks_with_aad_parameters[0]
2019/10/24 12:00:39 [TRACE] vertex "module.aks-cluster.azurerm_kubernetes_cluster.aks_with_aad_parameters[0]": visit complete
2019/10/24 12:00:39 [TRACE] vertex "module.aks-cluster.azurerm_kubernetes_cluster.aks_with_aad_parameters": dynamic subgraph encountered errors
2019/10/24 12:00:39 [TRACE] vertex "module.aks-cluster.azurerm_kubernetes_cluster.aks_with_aad_parameters": visit complete
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.aks-cluster.azurerm_monitor_diagnostic_setting.aks_cluster_diagnostics" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.aks-cluster.data.external.aks_agentpool_name" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.aks-cluster.azurerm_public_ip.aks_pip" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.aks-cluster.output.cluster_public_ip" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.aks-cluster.output.agentpoolname" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.aks-cluster.azurerm_monitor_diagnostic_setting.aks_nsg_diagnostics" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.redis-firewall-allow-aks.var.redis_firewall_start_ip" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "provider.external (close)" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "output.public_ip" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.redis-firewall-allow-aks.var.redis_firewall_end_ip" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "module.redis-firewall-allow-aks.azurerm_redis_firewall_rule.allow" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "provider.azurerm (close)" errored, so skipping
2019/10/24 12:00:39 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019-10-24T12:00:39.573+0100 [DEBUG] plugin: plugin process exited: path=/Users/rudolphjacksonm/tf/terraform/staging/.terraform/plugins/darwin_amd64/terraform-provider-azurerm_v1.35.0_x4 pid=67689 error="exit status 2"
2019-10-24T12:00:39.859+0100 [DEBUG] plugin: plugin exited
2019-10-24T12:00:39.862+0100 [DEBUG] plugin: plugin process exited: path=/Users/rudolphjacksonm/tf/terraform/staging/.terraform/plugins/darwin_amd64/terraform-provider-external_v1.2.0_x4 pid=67690
2019-10-24T12:00:39.863+0100 [DEBUG] plugin: plugin exited
```

**Comment by tombuildsstuff** [comment]
@rudolphjacksonm that's an unrelated crash which'll be fixed by #4697

**Comment by mbfrahry** [comment]
Hi @cwebbtw, I just took a look at this crash and we've updated some of the logic that made it occur. Could you confirm whether or not you're still seeing this in the latest version of the provider?

**Comment by cwebbtw** [comment]
I cannot reproduce this anymore on 1.37.0 👍

**Comment by mbfrahry** [comment]
Cheers! Thanks for checking @cwebbtw. Closing this down
