### ISSUE TITLE
Terraform crash with the resource azurerm_app_service 

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#4680]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.12
+ provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

Terraform [main file of the module is available here](https://github.com/JamesDLD/terraform-azurerm-Az-AppService/blob/master/main.tf).

### Panic Output

A Terraform [crash log file available here](https://github.com/JamesDLD/terraform-azurerm-Az-AppService/blob/master/examples/docker_python_hello_world/crash.log).

### Expected Behavior
I am working on a module that will create any App Service Environment, App Service and function.
The sample should create a Linux App Service running a Docker container as [explained here](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/app-service/docker-basic).

### Actual Behavior

1. Display the following error `Error: rpc error: code = Unavailable desc = transport is closing`
And
2. A Terraform [crash log file available here](https://github.com/JamesDLD/terraform-azurerm-Az-AppService/blob/master/examples/docker_python_hello_world/crash.log)

### Steps to Reproduce

1. git clone https://github.com/JamesDLD/terraform-azurerm-Az-AppService.git
2. `cd terraform-azurerm-Az-AppService/examples/docker_python_hello_world/`
3. `terraform init`
4. `terraform apply`

### References

* Linux App Service running a Docker container as [explained here](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/app-service/docker-basic).

**Comment by tombuildsstuff** [comment]
Crash log:

```
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: panic: interface conversion: interface {} is nil, not map[string]interface {}
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: goroutine 162 [running]:
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs(0x3e7ece0, 0xc000c3dd60, 0x4, 0x3e7ece0, 0xc000c3dd60, 0x1)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure/app_service.go:1256 +0xca9
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmAppServiceCreate(0xc00048d340, 0x3e18720, 0xc000616480, 0x2, 0x823b200)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_app_service.go:285 +0x148d
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000411800, 0xc000dad2c0, 0xc000d58840, 0x3e18720, 0xc000616480, 0xc000d6c801, 0xc000d52f60, 0x3f7a2e0)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:305 +0x3b4
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000506880, 0xc0007f3a30, 0xc000dad2c0, 0xc000d58840, 0xc000d53038, 0xc0000bda20, 0x3f7c620)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0x18f
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000bce80, 0x4b95d80, 0xc0008bc7e0, 0xc000633800, 0xc0000bce80, 0xc0008bc7e0, 0xc000667ba8)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:885 +0x894
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x42c4620, 0xc0000bce80, 0x4b95d80, 0xc0008bc7e0, 0xc000dad0e0, 0x0, 0x4b95d80, 0xc0008bc7e0, 0xc000d1a000, 0xba7)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000568300, 0x4be3780, 0xc0004e8d80, 0xc000b10100, 0xc000501170, 0x820f540, 0x0, 0x0, 0x0)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:972 +0x470
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000568300, 0x4be3780, 0xc0004e8d80, 0xc000b10100, 0x0)
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1252 +0xda6
2019-10-22T11:27:12.144+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003e110, 0xc000568300, 0x4be3780, 0xc0004e8d80, 0xc000b10100)
2019-10-22T11:27:12.145+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:691 +0x9f
2019-10-22T11:27:12.145+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-22T11:27:12.145+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.35.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

**Comment by JamesDLD** [comment]
I did solve this, did a wrong interpretation of the Conditional Expressions.
