### ISSUE TITLE
sigsegv importing network security group

### ISSUE THREAD

**Issue by clangaxon** [terraform-providers/terraform-provider-azurerm#553]
TF 0.10.8 ...

```
panic: runtime error: invalid memory address or nil pointer dereference
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x125f537]
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 
2017-11-13T12:02:51.525-0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/linux_amd64/terraform-provider-azurerm_v0.3.2_x4
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: goroutine 650 [running]:
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmNetworkSecurityGroupRead(0xc42204f7a0, 0x151fc60, 0xc4203c8000, 0x0, 0x1fe6b20)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_network_security_group.go:193 +0x477
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420313c80, 0xc42056b0e0, 0x151fc60, 0xc4203c8000, 0xc4202f1c20, 0xc420630701, 0x80000000000)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:321 +0x199
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420140930, 0xc42056b090, 0xc42056b0e0, 0x7fee77d95d90, 0x0, 0x18)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:284 +0x9a
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4201397c0, 0xc4205867f0, 0xc420587090, 0x0, 0x0)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: reflect.Value.call(0xc420366780, 0xc420384120, 0x13, 0x15e94fa, 0x4, 0xc420666f20, 0x3, 0x3, 0x0, 0xc4204e0000, ...)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/usr/local/go/src/reflect/value.go:434 +0x906
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: reflect.Value.Call(0xc420366780, 0xc420384120, 0x13, 0xc420899720, 0x3, 0x3, 0xc4208997c0, 0x7880d7, 0xc420e3d920)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: net/rpc.(*service).call(0xc4203641c0, 0xc420382000, 0xc420378150, 0xc420388400, 0xc42036e980, 0x139d460, 0xc4205867f0, 0x16, 0x139d4a0, 0xc420587090, ...)
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: created by net/rpc.(*Server).ServeCodec
2017-11-13T12:02:51.525-0800 [DEBUG] plugin.terraform-provider-azurerm_v0.3.2_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by clangaxon** [comment]
Confirmed still a problem in 0.3.3

**Comment by tombuildsstuff** [comment]
hey @clangaxon 

Thanks for opening this issue (and confirming that it's still an issue in 0.3.3) :)

So that we can understand this further would it be possible to know roughly when this Network Security Group was created (e.g. September 2017), in which region it exists, and how it was created (through ARM Templates/the Portal etc)? Historically resources created through different API versions can have different properties - which I believe is the cause of the issue here.

Thanks

**Comment by clangaxon** [comment]
I now can't repeat this.  It was Azure Canada Central and an old NSG (a year or more).  Feel free to close this if generally trapping this condition doesn't make sense. Thanks!

**Comment by tombuildsstuff** [comment]
@clangaxon apologies for the delayed response here - whilst we could update the code to handle this, I'd argue it shows an issue with the resource in Azure (since, the Azure API's explicit that a Location field must be returned in the response).

Regarding being unable to reproduce this - AFAIK any changes made to a resource (like an NSG) will update the state of the resource within Azure such that it includes the properties from the latest API version (in this case, Location would be added). As such, I'm going to close this for the moment - with a workaround of "make any change to the resource (such as adding a Tag etc) for the state to be updated" - which will avoid this crash (as the resource should then be up to date).

Thanks!
