### ISSUE TITLE
Crash if data azurerm_private_dns_zone does not exist

### ISSUE THREAD

**Issue by mjiderhamn** [terraform-providers/terraform-provider-azurerm#6926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azurerm v2.9.0
```

### Affected Resource(s)

* `data azurerm_private_dns_zone`

### Terraform Configuration Files

```hcl
data "azurerm_private_dns_zone" "foobar" {
  name = "foo"
  resource_group_name = "bar"
}
```

### Panic Output

https://gist.github.com/mjiderhamn/8767e81b6c51199188596bd4db439612

### Expected Behavior

If `data "azurerm_private_dns_zone"` is used for a non-existing Private DNS Zone, Terraform should inform that resource does not exist.

### Actual Behavior

If Private DNS Zone doesn't exist Terraform crashes.

### Important Factoids

In my case resource groups exists but Private DNS Zone does not.

**Comment by tombuildsstuff** [comment]
Panic:

```
2020-05-14T14:48:26.034+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 
2020-05-14T14:48:26.034+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/privateDnsZones/kofaxcloud.com' under resource group 'kofaxcloud-dns' was not found."}}
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: panic: runtime error: invalid memory address or nil pointer dereference
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0x37bec09]
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: goroutine 99 [running]:
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns.dataSourceArmPrivateDnsZoneRead(0xc000586380, 0x3c48a40, 0xc0001c8000, 0x0, 0x0)
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns/private_dns_zone_data_source.go:77 +0x299
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000882180, 0xc000d86a80, 0x3c48a40, 0xc0001c8000, 0xc0007f6980, 0x1, 0x0)
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:398 +0x8f
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000813400, 0xc0006699a0, 0xc000d86a80, 0xc000d86a80, 0x0, 0x0)
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:451 +0x96
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000194e10, 0x49a71a0, 0xc000ffdf20, 0xc0005f65c0, 0xc000194e10, 0xc000ffdf20, 0xc000da1a48)
2020-05-14T14:48:26.037+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:1036 +0x464
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x3ff6c00, 0xc000194e10, 0x49a71a0, 0xc000ffdf20, 0xc000d84300, 0x0, 0x49a71a0, 0xc000ffdf20, 0xc000602300, 0xfc)
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3225 +0x21e
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e62c0, 0x49e1aa0, 0xc000685c80, 0xc000c64100, 0xc0008ace10, 0x754a090, 0x0, 0x0, 0x0)
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:995 +0x467
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0xc0000e62c0, 0x49e1aa0, 0xc000685c80, 0xc000c64100, 0x0)
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1275 +0xd44
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0009167f0, 0xc0000e62c0, 0x49e1aa0, 0xc000685c80, 0xc000c64100)
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:710 +0xa8
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-05-14T14:48:26.038+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:708 +0xa8
```

**Comment by rhysjtevans** [comment]
This is frustrating,

**Comment by fabdouglas** [comment]
Still happens with:
```
Terraform v0.12.28
+ provider.azurerm v2.16.0
```
```
panic: runtime error: invalid memory address or nil pointer dereference
2020-06-30T20:12:03.694+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.16.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45d3d52]
2020-06-30T20:12:03.694+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.16.0_x5: 
2020-06-30T20:12:03.694+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.16.0_x5: goroutine 64 [running]:
2020-06-30T20:12:03.694+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.16.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns.dataSourceArmPrivateDnsZoneRead(0xc0009ea3f0, 0x4a1fd80, 0xc000404000, 0x0, 0x0)
2
```
