### ISSUE TITLE
Unexpected Error when running terraform plan

### ISSUE THREAD

**Issue by kensykora** [terraform-providers/terraform-provider-azurerm#6954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azuread v0.9.0
+ provider.azurerm v2.6.0
+ provider.random v2.2.1
```

I ran into an unexpected error when trying to run a terraform plan operation:

```
Error: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 65, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 51, in <module>
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\handlers.py", line 173, in doRollover
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\kensy\\.azure\\telemetry\\cache' -> 'C:\\Users\\kensy\\.azure\\telemetry\\cache.1'
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 68, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\telemetry.py", line 210, in _wrapper
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\telemetry.py", line 246, in conclude
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-telemetry\azure\cli\telemetry\__init__.py", line 64, in save
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-telemetry\azure\cli\telemetry\util.py", line 53, in save_payload
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"010bccf9-370a-4ded-9fd9-b7a824ed9594","Reserved.SequenceNumber":1,"Reserved.SessionId":"88256b74-4a94-44dd-8bb1-5f7dbb541d20","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"b1a1a760-1b8b-4219-9d3c-b28e645cf11e","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.3.1@none","Context.Default.VS.Core.MacAddressHash":"381a9872d078bd3faca4b3442d1b50092f0ee657b4bdfc49003648757dd19e31","Context.Default.VS.Core.Machine.Id":"381a9872-d078-bd3f-aca4-b3442d1b5009","Context.Default.VS.Core.OS.Type":"windows","Context.Default.VS.Core.OS.Version":"10.0.18362","Context.Default.VS.Core.User.Id":"068b7790-7cdd-11ea-afd8-0c7a15a01fe9","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.3.1","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"f93dc8e8-96c1-11ea-8d40-0c7a15a01fe9","Context.Default.AzureCLI.CoreVersion":"2.3.1","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"068b7790-7cdd-11ea-afd8-0c7a15a01fe9","Context.Default.AzureCLI.ShellType":"cmd","Context.Default.AzureCLI.UserAzureId":"82a16f2bb2557dc57e8b304e893fd0344c4c71b4f4a6f2af537af2d8bfc8ac47","Context.Default.AzureCLI.UserAzureSubscriptionId":"dd35fb95-c908-4eb0-a904-2ec12d91e0cb","Context.Default.AzureCLI.DefaultOutputType":"table","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,cp1252","Context.Default.AzureCLI.StartTime":"2020-05-15 15:37:24.262188","Context.Default.AzureCLI.EndTime":"2020-05-15 15:37:24.921806","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--resource,--subscription,-o","Context.Default.AzureCLI.PythonVersion":"3.6.6","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"MSI"}}]}'
Arguments: ()

  on ..\..\modules\_global\main.tf line 11, in provider "azurerm":
  11: provider "azurerm" {
```

This only happened one time, and fixed itself on subsequent runs. I wasn't doing anything concurrently as this was happening, so maybe a minor race condition?

**Comment by kensykora** [comment]
This happened in 0.10.0 as well

```
Error: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 65, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 51, in <module>
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\handlers.py", line 169, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\kensy\\.azure\\telemetry\\cache.2' -> 'C:\\Users\\kensy\\.azure\\telemetry\\cache.3'
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 68, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\telemetry.py", line 210, in _wrapper
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\telemetry.py", line 246, in conclude
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-telemetry\azure\cli\telemetry\__init__.py", line 64, in save
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-telemetry\azure\cli\telemetry\util.py", line 53, in save_payload
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"70c17b72-c5ea-451d-9623-e2ca2ba0bb0f","Reserved.SequenceNumber":1,"Reserved.SessionId":"2b3fd807-08bc-41ad-b885-a84671a0cc17","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"4c3c57e9-1855-4212-b4b5-f91044001509","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.3.1@none","Context.Default.VS.Core.MacAddressHash":"381a9872d078bd3faca4b3442d1b50092f0ee657b4bdfc49003648757dd19e31","Context.Default.VS.Core.Machine.Id":"381a9872-d078-bd3f-aca4-b3442d1b5009","Context.Default.VS.Core.OS.Type":"windows","Context.Default.VS.Core.OS.Version":"10.0.18362","Context.Default.VS.Core.User.Id":"068b7790-7cdd-11ea-afd8-0c7a15a01fe9","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.3.1","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"cb5ca778-9785-11ea-9b17-0c7a15a01fe9","Context.Default.AzureCLI.CoreVersion":"2.3.1","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"068b7790-7cdd-11ea-afd8-0c7a15a01fe9","Context.Default.AzureCLI.ShellType":"cmd","Context.Default.AzureCLI.UserAzureId":"REMOVED","Context.Default.AzureCLI.UserAzureSubscriptionId":"REMOVED","Context.Default.AzureCLI.DefaultOutputType":"table","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,cp1252","Context.Default.AzureCLI.StartTime":"2020-05-16 14:59:08.648300","Context.Default.AzureCLI.EndTime":"2020-05-16 14:59:09.318814","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--resource,--subscription,-o","Context.Default.AzureCLI.PythonVersion":"3.6.6","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"MSI"}}]}'
Arguments: ()

  on main.tf line 101, in provider "azurerm":
 101: provider "azurerm" {
```

That resource is this:

```hcl
provider "azurerm" {
  alias           = "prod"
  subscription_id = local.subscriptions.prod
  features {}

  skip_provider_registration = true
}
```

Similar to the original post, running `terraform plan` fixes it

**Comment by sean-nixon** [comment]
I've seen this same issue locally on MacOS as well. It's sporadic but frustrating. I believe I was running 2.8.0 or 2.9.0 when I last saw the issue. As an attempted workaround, I disabled Azure CLI telemetry and haven't seen it since, but it's not a frequent enough issue that I can say it's a confirmed fix. https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest

In my `~/.azure/config`:
```
[core]
collect_telemetry = false
```
