### ISSUE TITLE
azurerm_frontdoor custom https-configuration error when updating send-receive timeout value

### ISSUE THREAD

**Issue by naqeeb-dentsu** [terraform-providers/terraform-provider-azurerm#9075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
Terraform v0.12.10
+ provider.azurerm v2.32.0
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl

  < snipped >

resource "azurerm_frontdoor" "fd" {
  name                                         = terraform.workspace
  resource_group_name                          = azurerm_resource_group.fd.name
  enforce_backend_pools_certificate_name_check = false
  backend_pools_send_receive_timeout_seconds   = local.send_receive_timeout

  frontend_endpoint {
    name                              = terraform.workspace
    host_name                         = "${terraform.workspace}.azurefd.net"
    custom_https_provisioning_enabled = false
  }

  // Frontends
  dynamic "frontend_endpoint" {
    for_each = local.app_config
    content {
      name                              = replace(frontend_endpoint.value["host_name"], ".", "-")
      host_name                         = frontend_endpoint.value["host_name"]
      session_affinity_enabled          = "false"
      session_affinity_ttl_seconds      = "0"
      custom_https_provisioning_enabled = true
      custom_https_configuration {
        certificate_source = "FrontDoor"
      }
    }
  }

  < snipped >

}
```

### Debug Output

Terraform plan output:
[Plan output gist](https://gist.github.com/naqeeb-dentsu/843d21dd780202dac7adeef6c2d5bbd2#file-terraform_plan-txt)

Initial Terraform apply output:
[First apply output gist](https://gist.github.com/naqeeb-dentsu/843d21dd780202dac7adeef6c2d5bbd2#file-initial_terraform_apply-txt)

Subsequent Terraform apply output:
[Second apply output gist](https://gist.github.com/naqeeb-dentsu/843d21dd780202dac7adeef6c2d5bbd2#file-subsequent_terraform_apply-txt)

### Expected Behavior

In place change in value of `azurerm_frontdoor.fd.backend_pools_send_receive_timeout_seconds` from `240` to `239`.

### Actual Behavior

The follow error occurs:

Note: There should be no change to the custom http configuration for the frontend-endpoint according to the `terraform plan` output.
```
Error: updating Custom HTTPS configuration for Frontend Endpoint "adverity-wal-int-masked-com" (Front Door "nonprod-1-afd" / Resource Group "nonprod-1-afd-rg"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "adverity-wal-int-masked-com" (Resource Group "nonprod-1-afd-rg"): enabling Custom Domain HTTPS for Frontend Endpoint: frontdoor.FrontendEndpointsClient#EnableHTTPS: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="That action isn’t allowed in this profile."

  on ../modules/azurerm-frontdoor-tf12/main.tf line 187, in resource "azurerm_frontdoor" "fd":
 187: resource "azurerm_frontdoor" "fd" {
```

Subsequent execution of `terraform apply` with exactly the same configuration results in no error, and the change can be confirmed to have been completed in Azure Portal.

### Steps to Reproduce

1. `Change 'backend_pools_send_receive_timeout_seconds' value within an already deployed Front Door resource, which is using managed certificate configuration for Front Door Front-Ends.`
2. `terraform plan`
3. `terraform apply`
4. `terraform apply`

### Important Factoids

* Front door resource was initially deployed using azurerm provider version 1.44.0.
    * Upgraded due to requirement to customize send-receive timeout.
    * send-receive timeout customization introduced in V2.8.0, same issue is present when configuring.
    * issue is also present with azurerm V2.24.0, noted as remediation to similar issue ([#8036](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8036)).

### References

* [#8036](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8036)

**Comment by kingsleyadam** [comment]
I'm getting this even without changing `backend_pools_send_receive_timeout_seconds`. I have a very similar setup, using FrontDoor as the `certificate_source`. On the first run, it succeeds. For all other runs that have a change, I get the error.

```
Custom Domain HTTPS for Frontend Endpoint: frontdoor.FrontendEndpointsClient#EnableHTTPS: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="That action isn’t allowed in this profile."
```

**Comment by akshaychopra5207** [comment]
Can you please provide the ETA for this bug Fix?

**Comment by naqeeb-dentsu** [comment]
> Can you please provide the ETA for this bug Fix?

Hi, sorry I'm unaware of one. We have rolled back (through redeploying) our infrastructure to azurerm V1.44.0 and it is stable now.

**Comment by JayDoubleu** [comment]
I only have below in my configuration: 
```
  frontend_endpoint {
    name                                    = "someone"
    host_name                               = "someone"
    custom_https_provisioning_enabled       = true
  }
```

When trying to create custom domain with https endpoint (managed by azure)
I am getting a terraform crash.
```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [0] with length 0
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: goroutine 163 [running]:
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor.updateCustomHttpsConfiguration(0x581d2a0, 0xc001f18300, 0xc0006f6d10, 0x0, 0x868bef0, 0x0, 0x0, 0x1, 0xc0010506f0, 0x24, ...)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor/frontdoor_custom_https_configuration_resource.go:221 +0x9ac
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor.resourceFrontDoorCreateUpdate(0xc001e64690, 0x4aa95a0, 0xc001b34000, 0x0, 0x0)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor/frontdoor_resource.go:585 +0x189e
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000ccaa20, 0xc001551a40, 0xc001e9c1c0, 0x4aa95a0, 0xc001b34000, 0x4ad3101, 0xc00023a688, 0xc001e9bf20)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:316 +0x273
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000124780, 0xc00148da10, 0xc001551a40, 0xc001e9c1c0, 0xc001e482c8, 0xc00000f950, 0x4ad5380)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00011d770, 0x581d2e0, 0xc001bb2ab0, 0xc00198b8f0, 0xc00011d770, 0xc001bb2ab0, 0xc000858b78)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8ab
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x4f04d40, 0xc00011d770, 0x581d2e0, 0xc001bb2ab0, 0xc0018a47e0, 0x0, 0x581d2e0, 0xc001bb2ab0, 0xc001bf0000, 0x2857)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000583200, 0x5862d80, 0xc000643080, 0xc0001d5800, 0xc00097ba10, 0x864c040, 0x0, 0x0, 0x0)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x522
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc000583200, 0x5862d80, 0xc000643080, 0xc0001d5800, 0x0)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd34
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00027a1e0, 0xc000583200, 0x5862d80, 0xc000643080, 0xc0001d5800)
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa5
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-18T09:23:24.740Z [DEBUG] plugin.terraform-provider-azurerm_v2.43.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa5
2021-01-18T09:23:24.746Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.43.0/linux_amd64/terraform-provider-azurerm_v2.43.0_x5 pid=16605 error="exit status 2"
2021/01/18 09:23:24 [DEBUG] module.tfMain.azurerm_frontdoor.Web_01: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/18 09:23:24 [TRACE] EvalWriteState: recording 3 dependencies for module.tfMain.azurerm_frontdoor.Web_01
2021/01/18 09:23:24 [TRACE] EvalWriteState: writing current state object for module.tfMain.azurerm_frontdoor.Web_01
2021/01/18 09:23:24 [TRACE] EvalApplyProvisioners: azurerm_frontdoor.Web_01 is not freshly-created, so no provisioning is required
2021/01/18 09:23:24 [TRACE] EvalWriteState: recording 3 dependencies for module.tfMain.azurerm_frontdoor.Web_01
2021/01/18 09:23:24 [TRACE] EvalWriteState: writing current state object for module.tfMain.azurerm_frontdoor.Web_01
2021/01/18 09:23:24 [TRACE] vertex "module.tfMain.azurerm_frontdoor.Web_01": visit complete
2021/01/18 09:23:24 [TRACE] dag/walk: upstream of "module.tfMain (close)" errored, so skipping
2021/01/18 09:23:24 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2021/01/18 09:23:24 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/18 09:23:24 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-01-18T09:23:24.923Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
